feat: add validator ui support for pipeline templates
screwdriver-cd/ui pull request #1010
Opened 2024-03-07 20:03 UTC by pritamstyz4ever

## Context

Added validator support to display pipeline template and pipeline template usage

## Objective

The validator should correctly display the pipeline template name, namespace, jobs, etc.
The validator should correctly display the pipeline template used in a pipeline

Template:
<img width="1672" alt="Screenshot 2024-03-06 at 7 17 55 PM" src="https://github.com/screwdriver-cd/ui/assets/4926830/4b6af553-00d6-49d7-ac0a-6ba60b183bb3">
<img width="1680" alt="Screenshot 2024-03-06 at 7 18 03 PM" src="https://github.com/screwdriver-cd/ui/assets/4926830/37316f1b-2fee-495b-8e7f-f6dd12036e06">

Usage:
<img width="1914" alt="Screenshot 2024-03-07 at 2 41 11 PM" src="https://github.com/screwdriver-cd/ui/assets/4926830/5e8c30b3-dda4-45ca-b9f0-8c79295dd59b">

## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2024-03-07 20:51 UTC, jithine submitted a review, later dismissed

2024-03-07 21:13 UTC, sagar1312 requested changes

2024-03-07 21:13 UTC, sagar1312 commented on tests/integration/components/validator-results/component-test.js
> +          },
We should use/render the configuration under `shared`.
If few jobs inherit `steps`, `settings` from shared, that is not being visualized in the validator results

2024-03-07 23:22 UTC, sagar1312 commented
Also the workflow is not visualized for pipeline template
We should show how the jobs are interconnected in the workflow graph

![image](https://github.com/screwdriver-cd/ui/assets/2124590/711565d1-6076-4597-849b-b9abd4261002)

2024-03-08 16:12 UTC, pritamstyz4ever commented
> Also the workflow is not visualized for pipeline template We should show how the jobs are interconnected in the workflow graph
> 
> ![image](https://private-user-images.githubusercontent.com/2124590/311067153-711565d1-6076-4597-849b-b9abd4261002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MTQ0NjksIm5iZiI6MTcwOTkxNDE2OSwicGF0aCI6Ii8yMTI0NTkwLzMxMTA2NzE1My03MTE1NjVkMS02MDc2LTQ1OTctODQ5Yi1iOWFiZDQyNjEwMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMTYwOTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWJlZjIxN2QyYWRiMDc2MjgzNDE4ZjM5ODc0NjMwM2YwZjcwMzk4OGMxZjAwMGVhYjI2NDZlZDk5OWU2OTE4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fKBLv6TTLJjV8AIrvKOIS33fWyEvxtrFDPbFqLs_cxo)

Current workflow jobs are not returned by the API for templates. We will need to add that

2024-03-08 16:31 UTC, pritamstyz4ever commented on tests/integration/components/validator-results/component-test.js
> +          },
I think shared steps have the same behavior as pipeline, for settings and environment we may need to tweak API to return the merged values

2024-03-08 17:59 UTC, sagar1312 commented
> > Also the workflow is not visualized for pipeline template We should show how the jobs are interconnected in the workflow graph
> > ![image](https://private-user-images.githubusercontent.com/2124590/311067153-711565d1-6076-4597-849b-b9abd4261002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MTQ0NjksIm5iZiI6MTcwOTkxNDE2OSwicGF0aCI6Ii8yMTI0NTkwLzMxMTA2NzE1My03MTE1NjVkMS02MDc2LTQ1OTctODQ5Yi1iOWFiZDQyNjEwMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMTYwOTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWJlZjIxN2QyYWRiMDc2MjgzNDE4ZjM5ODc0NjMwM2YwZjcwMzk4OGMxZjAwMGVhYjI2NDZlZDk5OWU2OTE4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fKBLv6TTLJjV8AIrvKOIS33fWyEvxtrFDPbFqLs_cxo)
> 
> Currently workflow jobs are not returned by the API for templates. We will need to add that

Yes, the validator API may need to all the config-parser again to merge the `shared` into `jobs`. That would also generate workflow graph.

2024-03-08 20:32 UTC, VonnyJap commented
@sagar1312 

> Also the workflow is not visualized for pipeline template
> We should show how the jobs are interconnected in the workflow graph

We can do the visualization as next item to work on. At least the validator can make sure that the config in template is working. Although yes, I agree, without the workflow graph, pipeline template validator is missing the important purpose and becomes mainly just to validate the syntax.

2024-03-08 21:38 UTC, sagar1312 commented
> @sagar1312
> 
> > Also the workflow is not visualized for pipeline template
> > We should show how the jobs are interconnected in the workflow graph
> 
> We can do the visualization as next item to work on. At least the validator can make sure that the config in template is working. Although yes, I agree, without the workflow graph, pipeline template validator is missing the important purpose and becomes mainly just to validate the syntax.

Sure, we can push changes incrementally. 
Besides visualizing workflow graph, we also need to make sure config under `shared` as explained earlier needs to be somehow (merging it with `jobs`) displayed in the result.

2024-03-08 21:39 UTC, sagar1312 approved these changes

2024-03-08 22:32 UTC, sagar1312 approved these changes

2024-03-08 22:33 UTC, merged

2024-03-14 17:31 UTC, adong commented
Validator: https://cd.screwdriver.cd/validator

```
template: sd-test/example-template@latest
shared:
    environment: 
        FOO: bar
```