WIP: New look and feel for event page
screwdriver-cd/ui pull request #1040
Opened 2024-04-18 19:08 UTC by adong

## Context

Modernize event page:

1) Add navigation from old ui to new ui and vice versa to sd admins
2) Move options from top to left side
3) Move events/pull-requests from right side to left side along combining jobs(job-list-view)

![image](https://github.com/screwdriver-cd/ui/assets/15989893/a298feaf-e9b7-48e9-acec-78c3e8351226)

Pending:

1) Change the event-list view layout from right to left
2) Change the workflow-graph view layout from left to right
3) Tests are not written until logics are finalized.

## Objective
Screenshot:

![image](https://github.com/screwdriver-cd/ui/assets/15989893/b636a9f9-02c0-466d-baa6-9fa5e1574ff0)

![image](https://github.com/screwdriver-cd/ui/assets/15989893/38d6c218-02b9-4826-9e0c-0e829c924ab5)

## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2024-04-25 04:39 UTC, VonnyJap commented
tests failed, expected?

2024-05-03 16:39 UTC, minghay requested changes

2024-05-03 16:39 UTC, minghay commented on app/styles/new-ui.scss
> +        'pipeline-content pipeline-content pipeline-workflowgraph pipeline-workflowgraph pipeline-workflowgraph';
```suggestion
      grid-template-areas:
        'pipeline-header  pipeline-header'
        'pipeline-tab     pipeline-tab'
        'pipeline-content pipeline-workflowgraph';
```
This should make it easier to read and then you can set the width of `pipeline-content` and `pipeline-workflowgraph`.

2024-05-03 16:39 UTC, minghay commented on app/v2/route.js
> +}
`AuthenticatedRouteMixin` is deprecated.  You should refactor this to:
```suggestion
import Route from '@ember/routing/route';
import { service } from '@ember/service';

export default class NewRoute extends Route {
  @service session;

  @service router;

  beforeModel(transition) {
    this.session.requireAuthentication(transition, 'login');
    
    const isAdmin = (this.session.data.authenticated.scope || []).includes('admin');
    if (!isAdmin) {
      this.router.transitionTo('/404');
    }
  }
}
```

2024-05-03 16:39 UTC, minghay commented on app/v2/route.js
> +}
Also note, all child routes are now protected by the session.

2024-05-03 16:39 UTC, minghay commented on app/components/app-header/component.js
> +  isAdmin: computed('session.data.authenticated.token', function isAdmin() {
See comment below on how to use the scope directly instead of decoding the JWT

2024-05-03 16:39 UTC, minghay commented on app/components/newui-pipeline-nav/component.js
> +// import Component from '@glimmer/component';
You should use the glimmer component instead of the legacy component

2024-05-03 16:39 UTC, minghay commented on app/router.js
> +    this.route('home');
Do you need this route yet?

2024-05-03 16:39 UTC, minghay commented on app/router.js
> +    this.route(
Do you need this route tree yet?

2024-05-03 17:14 UTC, adong commented on app/components/newui-pipeline-nav/component.js
> +// import Component from '@glimmer/component';
This one is needed because the scoped css style. If I use glimmer component, the style will not be applied and have to be added to the `app.scss` to import there manually. That's why I left there. 

I think this can be refactored to glimmer class, once we migrate all from the legacy components to glimmer components

2024-05-03 17:17 UTC, adong commented on app/router.js
> +    this.route(
Is it for line 150 dashboards? Dashboards are not needed right now.

2024-05-03 18:23 UTC, adong commented on app/router.js
> +    this.route(
Removed `v2.dashboard.*` routes

2024-05-03 22:27 UTC, minghay approved these changes

2024-05-04 03:39 UTC, tkyi approved these changes

2024-05-04 03:39 UTC, merged

2024-05-06 16:28 UTC, adong commented on app/router.js
> +    this.route(
New PR to remove routes from router.js https://github.com/screwdriver-cd/ui/pull/1048