[New UI] Code refactoring
screwdriver-cd/ui pull request #1055
Opened 2024-05-14 21:31 UTC by adong

## Context

## Objective

## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2024-05-21 22:26 UTC, minghay requested changes

2024-05-21 22:26 UTC, minghay commented on app/components/newui-event-card/styles.scss
> +  font-family: Helvetica, Arial, sans-serif;
This should safe to remove

2024-05-21 22:26 UTC, minghay commented on app/components/newui-event-card/styles.scss
> +    font-style: normal;
These should safe to remove

2024-05-21 22:26 UTC, minghay commented on app/components/newui-event-card/styles.scss
> +    font-weight: 400;
These should safe to remove

2024-05-21 22:26 UTC, minghay commented on tests/integration/components/newui-event-card/component-test.js
> +import Service from '@ember/service';
```suggestion
import sinon from 'sinon';
```

2024-05-21 22:26 UTC, minghay commented on tests/integration/components/newui-event-card/component-test.js
> +    this.owner.register('service:userSettings', userSettingsStub);
```suggestion
    const userSettings = this.owner.lookup('service:user-settings');
    sinon.stub(userSettings, 'getUserPreference').resolves({timestampFormat: 'UTC'});
```

2024-05-21 22:26 UTC, minghay commented on app/v2/pipeline/index/route.js
> +    if (pipeline.get('childPipelines')) {
```suggestion
    if (pipeline.childPipelines) {
```

2024-05-21 22:48 UTC, minghay commented on tests/integration/components/newui-event-card/component-test.js
> +import Service from '@ember/service';
You'll need to add `sinon` to the dev dependencies and can also remove `ember-sinon`

2024-05-22 17:55 UTC, adong commented on app/v2/pipeline/styles.scss
> +        }
@minghay good point, I'm still thinking it can be re-used for `pull-request` route. If it's not re-used, I can refactor and split into a different style sheet.

2024-05-22 19:11 UTC, adong commented on app/v2/pipeline/events/index/route.js
> +        : get(model, 'events.firstObject.id');
I made the changes, and it needs to be reverted back. See error

![image](https://github.com/screwdriver-cd/ui/assets/15989893/2f2b2b26-67e5-4158-a334-9025908e47a0)

2024-05-22 22:19 UTC, minghay approved these changes

2024-05-22 23:29 UTC, merged