fix(1749): Add ability to download artifact directory
screwdriver-cd/ui pull request #1195
Opened 2024-10-16 18:23 UTC by tkyi

## Context

Should be able to download artifacts by directory.

## Objective

This PR adds ability to download artifact directory.

## References

Related to https://github.com/screwdriver-cd/screwdriver/issues/1749

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2024-10-18 18:57 UTC, minghay requested changes

2024-10-18 18:57 UTC, minghay commented on app/components/artifact-tree/component.js
> +          });
```suggestion
```

2024-10-18 18:57 UTC, minghay commented on app/components/artifact-tree/component.js
> +            type: 'file'
```suggestion
```

2024-10-18 18:57 UTC, minghay commented on app/components/artifact-preview/component.js
> +      let downloadLink = this.iframeUrl.replace(
Don't use the `iframeUrl` as it doesn't get set properly (I'm not currently sure why the tree structure isn't setting it properly for directories).

Inject the Ember router service into this component and you can use the `.currentRoute` property to extract the artifact path within it:
```javascript
  this.router.currentRoute.params.file_path
```

The artifact that is returned as a string will have trailing `/` for directories, so you can use that to do the rest of the needed work of recreating the proper URL.

One last thing, you'll need to recreate the base API URL like what is down in the `downloadAll` function just below this function

2024-10-22 05:43 UTC, tkyi commented on app/components/artifact-preview/component.js
> +      let downloadLink = this.iframeUrl.replace(
updated

2024-10-22 16:46 UTC, minghay commented on app/components/artifact-preview/component.js
> +      if (this.type === 'directory') {
`this.type` is always undefined.  The type was set in code that was used in a previous library.

2024-10-23 17:28 UTC, minghay approved these changes

2024-10-23 17:28 UTC, merged