add button to toggle line wrapping
screwdriver-cd/ui pull request #587
Opened 2020-08-21 18:53 UTC by gcbw

## Context

Some times it is easier to read logs without line wrapping.

(build on top of the branch i had for #552 if this is desirable we can close that one and merge only this)

## Objective

This adds a button with the ellipsis icon `…` that toggles the existing long-line wrapping. Wrapping is still enabled by default, same as before.

line wrap, default, same as today:
<img width="986" alt="before" src="https://user-images.githubusercontent.com/16908116/90926189-7af2d680-e3a7-11ea-8cbb-add81b252956.png">

no line wrap.
<img width="983" alt="after" src="https://user-images.githubusercontent.com/16908116/90926201-7e865d80-e3a7-11ea-9617-c2ea17b66f54.png">

## References

N/a

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-08-24 17:48 UTC, tkyi commented
I like this idea
what do you think @adong @chasturansky?

2020-08-31 18:34 UTC, adong commented
> I like this idea
> what do you think @adong @chasturansky?

I like the functionality, but the number of buttons became bloated. It may be a good idea to re-design such.

2020-09-02 20:07 UTC, chasturansky commented
Hi @gcbw I help with the designs for SD. I think this is neat really like the full screen, I do think we can come up with a better icon for line-wrapping. Give me a couple of days to come up with that icon.

2020-09-24 17:19 UTC, adong requested changes

2020-09-24 17:19 UTC, adong commented on app/components/build-log/component.js
> +import { set, getWithDefault, computed, observer, togglerProperty } from '@ember/object';
Build Failed
``` broccoliBuilderErrorStack: SyntaxError: /sd/workspace/src/github.com/screwdriver-cd/ui/screwdriver-ui/components/build-log/component.js: @ember/object does not have a togglerProperty export```

I think its a typo `toggleProperty`

2020-09-25 17:34 UTC, adong commented on app/components/build-log/component.js
> +      toggleProperty(this, 'fullScreen');
Can you remove `toggleProperty`

```diff 
+++import { set, getWithDefault, computed, observer } from '@ember/object';

---import { set, getWithDefault, computed, observer, toggleProperty } from '@ember/object';

``` 

and use it directly.

`this.toggleProperty('fullScreen')`
`this.toggleProperty('lineWrap')`


Since `toggleProperty` isn't part of `@ember/object`

See ref: https://github.com/ember-codemods/ember-modules-codemod/issues/108

2020-09-25 19:42 UTC, gcbw commented
finally went ahead and used a vm with the proper node version to use the ember-cli version from this project. didn't want to break things for my more usual ones. apologies for all the small errors here.

2020-10-05 21:55 UTC, adong approved these changes

2020-10-05 23:30 UTC, merged