Job endpoint
screwdriver-cd/ui pull request #621
Opened 2020-10-30 08:32 UTC by OronNadiv

TBD (don't review/merge yet)

## Context

## Objective

## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-10-30 23:03 UTC, jithine approved these changes
few minor cleanups, LGTM

2020-10-30 23:05 UTC, OronNadiv commented on app/components/pipeline-graph-nav/styles.scss
>    .view-toggle {
Yes, just in case we want to use it in the future so it's good to keep it there.  This way it will be more visible to other devs.

2020-10-30 23:06 UTC, OronNadiv commented on app/pipeline/events/controller.js
> +/** */
It's part of the lint validation.  I can either remove the commend and add `eslint-ignore` or have an empty comment.  I'll go with the `eslint-ignore`

2020-10-30 23:12 UTC, jithine approved these changes

2020-10-30 23:39 UTC, adong commented on app/pipeline/jobs/index/route.js
> +export default Route.extend({
To use `routeAfterAuthentication`, this route needs to be extended from the following:

```
import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';

export default Route.extend(AuthenticatedRouteMixin, {
```

2020-10-31 00:16 UTC, adong commented
Builds button is not working any more.
![image](https://user-images.githubusercontent.com/15989893/97766453-9aa72900-1ad3-11eb-9936-9bf26329ad16.png)

2020-10-31 00:24 UTC, adong requested changes

2020-10-31 00:24 UTC, adong commented on app/components/pipeline-nav/template.hbs
> +  {{#nav.item}}{{#nav.link-to buildsLink}}Builds{{/nav.link-to}}{{/nav.item}}
`buildsLink` I think this is the issue. 

Options
1) Revert back to old
2) If you want to keep the flexibility to pass link, it also needs to see where 
```
{{pipeline-nav
```
being used and adds rest like `pipeline/secrets/template.hbs`, `pipeline/options/template.hbs`  `pipeline/options/metrics.hbs`  

3) Or, use this `{{or buildsLink "default"}}`

```hbs
  {{#nav.item}}{{#nav.link-to (or buildsLink "pipeline.events")}}Builds{{/nav.link-to}}{{/nav.item}}
```

I think 3rd option makes sense here

2020-10-31 00:35 UTC, adong commented on app/pipeline/events/controller.js
> +export async function startDetachedBuild(job, options = {}) {
I felt like this is [anti-pattern](https://deprecations.emberjs.com/v3.x/#toc_object-alias-method), refactoring so can be shared in two multiple controller is a good idea. 

Because `this` scope is tightly coupled, it
s kinda defeat the purpose... 

As far as suggestions, I dont have one, just wanted to point out here.

2020-10-31 03:30 UTC, OronNadiv commented on app/pipeline/jobs/index/route.js
> +export default Route.extend({
👍

2020-10-31 03:41 UTC, OronNadiv commented on app/pipeline/events/controller.js
> +export async function startDetachedBuild(job, options = {}) {
I totally agree.  Thanks for pointing it out.

2020-10-31 05:34 UTC, OronNadiv commented on app/components/pipeline-nav/template.hbs
> +  {{#nav.item}}{{#nav.link-to buildsLink}}Builds{{/nav.link-to}}{{/nav.item}}
Good catch.  I thought I tested it but apparently, I did not.
I fixed it using a new service.  Check out [this](https://github.com/screwdriver-cd/ui/pull/621/commits/e73baeaccf09e5cf78826a33b875c247da1d55bc) commit.

2020-10-31 05:36 UTC, OronNadiv commented on app/pipeline/jobs/index/controller.js
> +      // await this.createEvent(eventPayload, false);
done.

2020-10-31 05:37 UTC, OronNadiv commented on app/pipeline/jobs/index/route.js
> +export default Route.extend({
@adong are you sure it's required?  It already exists in the 'pipeline' route.  See [here](https://github.com/screwdriver-cd/ui/blob/master/app/pipeline/route.js#L6).

2020-10-31 16:47 UTC, ldong commented on app/components/pipeline-nav/component.js
> +  buildsLink: computed('pipelineService.buildsLink', function() {
Though I think using service is overkill, and it's okay.


Since dependent keys and return values are the same, you can use `alias` to shorten it.

```
import { alias } from '@ember/object/computed';

export default Component.extend({
  pipelineService: service('pipeline'),
  buildsLink: alias('pipelineService.buildsLink');
```

Nevertheless, just a minor comment, I'm approving the PR.

2020-10-31 16:48 UTC, adong commented on app/components/pipeline-nav/component.js
> +  pipelineService: service('pipeline'),
Though I think using service is overkill, and it's okay.


Since dependent keys and return values are the same, you can use `alias` to shorten it.

```
import { alias } from '@ember/object/computed';

export default Component.extend({
  pipelineService: service('pipeline'),
  buildsLink: alias('pipelineService.buildsLink');
```

Nevertheless, just a minor comment, I'm approving the PR.

2020-10-31 16:49 UTC, adong commented on app/pipeline/jobs/index/route.js
> +export default Route.extend({
Yes. I believe this causes the error if not extended from `AuthenticatedRouteMixin` : after session timeout, and log back in, not being redirected.

2020-10-31 16:50 UTC, adong approved these changes

2020-10-31 16:50 UTC, merged

2020-10-31 17:12 UTC, OronNadiv commented
@adong thanks for your diligent review, and your help with this feature.