Auto refresh
screwdriver-cd/ui pull request #628
Opened 2020-11-10 21:51 UTC by OronNadiv

## Context

In both workflow and list views, the user should be able to:
1. See new events/jobs as they triggered on other tabs/computers.
1. See a job starts/stops without clicking the "refresh" button.

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-11-11 00:31 UTC, jithine approved these changes

2020-11-11 03:54 UTC, adong commented on app/components/pipeline-list-view/component.js
> +    const isEqualRes = isEqual(rows.map(r => r.job), lastRows.map(r => r.job));
I'm not sure if the response returns jobs in a consistent order, maybe we need to `sort` before comparing.

2020-11-11 04:01 UTC, adong commented on app/components/pipeline-list-view/component.js
> +    const isEqualRes = isEqual(rows.map(r => r.job), lastRows.map(r => r.job));
I could be wrong, but I don't think the observer's function has parameters.

```
jobsObserverFunc({ jobsDetails }) {
    const rows = this.getRows(jobsDetails);
```

So this function always sets the table with new rows.

2020-11-11 04:03 UTC, adong commented on app/pipeline/jobs/index/controller.js
> +import { SHOULD_RELOAD_SKIP, SHOULD_RELOAD_YES } from '../../../mixins/model-reloader';
Ember know the relative path pain, and you could change the syntax from 

`'../../../mixins/model-reloader';`

to 

`'screwdriver-ui/mixins/model-reloader';`

2020-11-11 04:12 UTC, adong commented on app/pipeline/jobs/index/controller.js
> +      await this.refreshListViewJobs();
I dont think this guarantees `model()` is fetched and loaded when line `this.refreshListViewJobs()` runs.

2020-11-11 04:14 UTC, adong commented on app/pipeline/jobs/index/controller.js
> +      set(this, 'lastRefreshed', moment().subtract(1, 'day'));
`moment().subtract(1, 'day')`, I don't get the logic here, why the date is set to yesterday?

2020-11-11 04:16 UTC, adong requested changes
👀

2020-11-11 21:12 UTC, OronNadiv commented on app/pipeline/jobs/index/controller.js
> +import { SHOULD_RELOAD_SKIP, SHOULD_RELOAD_YES } from '../../../mixins/model-reloader';
👍

2020-11-11 21:13 UTC, OronNadiv commented on app/pipeline/jobs/index/controller.js
> +      set(this, 'lastRefreshed', moment().subtract(1, 'day'));
I wanted to reset the "lastRefreshed" value to trigger another refresh.

2020-11-11 21:27 UTC, OronNadiv commented on app/components/pipeline-list-view/component.js
> +    const isEqualRes = isEqual(rows.map(r => r.job), lastRows.map(r => r.job));
Done. 👍

2020-11-11 21:53 UTC, OronNadiv commented on app/pipeline/jobs/index/controller.js
> +      await this.refreshListViewJobs();
Good point but I can't find a use-case where refreshListViewJobs does not refresh the list.

2020-11-12 08:06 UTC, adong approved these changes
Looks good to me 👍

2020-11-12 08:06 UTC, adong commented on app/components/pipeline-list-view/component.js
> +    const rows = this.getRows(jobsDetails);
I have to say that I didn't think there would be parameters for observer function,  and I was wrong.

It indeed has
```
observer('value', function(sender, key, value, rev) {
```

see Ref: https://api.emberjs.com/ember/3.20/classes/Observable/methods

2020-11-12 08:06 UTC, adong commented on app/components/pipeline-list-view/component.js
> +    );
👍

2020-11-12 08:06 UTC, adong commented on app/pipeline/jobs/index/controller.js
> +      await this.refreshListViewJobs();
It's okay.

2020-11-12 17:22 UTC, jithine approved these changes

2020-11-12 17:27 UTC, merged