feat(2267): refactor collection page and apply lazy loading
screwdriver-cd/ui pull request #633
Opened 2020-11-17 17:30 UTC by klu909

## Context

## Objective

## References

https://github.com/screwdriver-cd/screwdriver/issues/2267

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-11-30 21:24 UTC, adong commented on app/components/collection-table-row/template.hbs
> +  {{#if queryError}}
What `queryError` could be?

2020-11-30 21:25 UTC, adong commented on app/components/pipeline-card/component.js
> +  updated: and('eventsInfo', 'lastEventInfo'),
Can we rename `updated` to `hasBothEventsAndLatestInfo` ? Latter is more intuitive.

2020-11-30 21:27 UTC, adong requested changes
Please add some descriptions to this PR.

2020-11-30 21:35 UTC, klu909 commented on app/components/collection-table-row/template.hbs
> +  {{#if queryError}}
if store query fails, for example getting 402 or 404 for whatever reason

2020-11-30 21:35 UTC, klu909 commented on app/components/collection-table-row/template.hbs
> +  {{#if queryError}}
it's just a boolean

2020-12-02 01:28 UTC, adong approved these changes

2020-12-02 10:43 UTC, merged