fix: Should not fail when validating template yamls that start with blank lines or dashes
screwdriver-cd/ui pull request #682
Opened 2021-03-23 23:40 UTC by tkyi

## Context

Validation fails in the UI when trying to validate templates that start with blank lines or dashes.
Example: 
```
---
name: sd/template-publish
version: "1.0"
description: Template for publishing templates
maintainer: foo@bar.com
config:
  image: node:8
  steps:
  - install_binaries: npm i -g screwdriver-template-main
  - publish_template: |
      template-publish | tee /tmp/publish.output
```
## Objective

This PR fixes to support template yamls padded by blank lines or dashes.
The UI was originally checking if the yaml starts with `name`. Now it will check for `name: ` key as well.

## References

N/A

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-03-23 23:44 UTC, vnugopal approved these changes

2021-03-24 03:27 UTC, adong requested changes

2021-03-24 03:27 UTC, adong commented on app/validator/service.js
> +    return /^name|\nname: |\nnamespace: /.test(yaml);
`\n` will only work for 1 line, maybe `\n+`?

2021-03-24 17:03 UTC, adong approved these changes

2021-03-24 17:04 UTC, merged