fix(2395): Make collection list available in copyTo dropdown on collection view component
screwdriver-cd/ui pull request #685
Opened 2021-03-27 09:59 UTC by kprasadpvv

## Context

- Available collection list is not displaying under copy to option in default pipeline collection dashboard.

## Objective

- As `model.collections` is not available I'm getting the collection list from store and using it directly in the component instead of passing it from parent component.

## References

https://github.com/screwdriver-cd/screwdriver/issues/2395

##Screenshots:
- Before Fix:

<img width="1639" alt="NoCollectionListUnderCopyToOption" src="https://user-images.githubusercontent.com/10308692/112503259-c7c0e480-8db0-11eb-809b-74df88549b9e.png">

- After Fix:

<img width="1643" alt="Screenshot 2021-03-27 at 3 27 45 PM" src="https://user-images.githubusercontent.com/10308692/112717194-0a99ce00-8f11-11eb-894d-bc4ef2fa8367.png">

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-03-29 17:32 UTC, adong requested changes

2021-03-29 17:32 UTC, adong commented on app/components/collection-view/component.js
> +      const collections = this.store.peekAll('collection');
Though this uses `store.peek`, but it listens to `store` changes. Could be expensive on every store changes, is there a better way 🤔?

2021-03-30 16:08 UTC, kprasadpvv commented on app/components/collection-view/component.js
> +      const collections = this.store.peekAll('collection');
Yeah, getting `collections` on component initiation is enough no need to inject `store` as dependency. So, removed it.

Thank you,
kp.

2021-03-30 16:09 UTC, kprasadpvv commented on app/components/collection-view/component.js
> +              reset: true,
To reset `pipeline selected` checkbox after successfully copy or remove operation along with reseting selectedArray.

2021-04-13 18:19 UTC, adong approved these changes

2021-04-13 20:06 UTC, merged