feat(2346): Support for job level parameters
screwdriver-cd/ui pull request #754
Opened 2021-11-05 17:21 UTC by sagar1312

## Context

## Objective

## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-11-18 20:28 UTC, adong commented on app/components/pipeline-event-row/component.js
> +        if (keys.length === 1 && keys[0] === 'value') {
// if (keys.length === 1 && keys[0] === 'value') { 
 
I don't follow the logics here. It's not obvious to me how to distinguish between job level and pipeline level parameters.

2021-11-18 20:28 UTC, adong commented on app/components/pipeline-event-row/component.js
> +  isCommitterDifferent: computed(
Thank you.

2021-11-18 20:37 UTC, adong commented
Looks like validator works fine.
![image](https://user-images.githubusercontent.com/15989893/142492882-2ab43bc5-12f5-4fb3-ba5f-d6b7cc75886d.png)

2021-11-18 20:44 UTC, adong commented
For brand new pipelines, only shared parameters shows up, job level parameters does not show.
![image](https://user-images.githubusercontent.com/15989893/142493468-ead13c94-d90b-414b-817f-c58b6e231f9f.png)

It shows after kick off the 1st build.

2021-11-18 20:47 UTC, adong commented on app/components/pipeline-event-row/component.js
> +        if (keys.length === 1 && keys[0] === 'value') {
![image](https://user-images.githubusercontent.com/15989893/142493751-aeef64a5-8c94-499d-8017-4ad2d9adf452.png)

![image](https://user-images.githubusercontent.com/15989893/142493836-6a3bbe57-7457-4ec8-923b-ba7aa871a886.png)

So for parameters, if its pipeline level, then key will be the pipeline level key, and value will be an object with single object such as 

```
{
    "main": {    // job name
        "p1": {    // job level
            "value": "main p1"
        },
        "p2": {  // job level
            "value": "parameter name for main job"
        }
    },
    "p1": {     // pipeline level
        "value": "p1"
    },
    "p2": {   // pipeline level
        "value": "adong123123"
    }
}
```

if it's job level parameters, the job name will be the key, and the values will be a nested object.

2021-11-18 20:56 UTC, adong commented
1) Add a job name also names p1
```
shared:
    image: node:14

parameters:
  p1: p1
  p2:
      value: adong
      description: User running build

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - p1: echo $(meta get parameters.p1)
            - p2: echo $(meta get parameters.p2)

        parameters:
            p1: main p1
            p2:
                value: parameter name for main job
                description: This is a job parameter desc
    p1:
        requires: [~pr, ~commit]
        steps:
            - p1: echo $(meta get parameters.p1)
            - p2: echo $(meta get parameters.p2)
        parameters:
            p1: p1's p1
```

![image](https://user-images.githubusercontent.com/15989893/142494934-3bbc7033-5e7c-4945-b6fe-ef89497c5656.png)

2) Remove p1 from pipeline's parameters
```
shared:
    image: node:14

parameters:
  p2:
      value: adong
      description: User running build

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - p1: echo $(meta get parameters.p1)
            - p2: echo $(meta get parameters.p2)

        parameters:
            p1: main p1
            p2:
                value: parameter name for main job
                description: This is a job parameter desc
    p1:
        requires: [~pr, ~commit]
        steps:
            - p1: echo $(meta get parameters.p1)
            - p2: echo $(meta get parameters.p2)
        parameters:
            p1: p1's p1
```
![image](https://user-images.githubusercontent.com/15989893/142495235-b635edce-fa97-45d6-ba8e-8fcae8948bef.png)

I tired few cases, and they look good to me.

2021-11-18 20:56 UTC, adong approved these changes

2021-11-18 20:57 UTC, adong requested changes

2021-11-18 20:57 UTC, adong commented on app/components/pipeline-event-row/component.js
> +    function numberOfParameters() {
I felt something here caused the display issue when pipeline is brand new and has no builds

2021-11-18 21:09 UTC, adong commented
For _restart_ case:  If I restart on job p1, somehow main's job parameters still show up. I guess that's okay. Because `p1` could be an upstream job which triggers `main`

![image](https://user-images.githubusercontent.com/15989893/142496898-b91f9af3-347d-4600-a82e-fbaf89a955b6.png)

2021-11-23 18:15 UTC, sagar1312 commented
> ~Looks like validator works fine.~
> 
> Actually, it does not show individual jobs' parameters ![image](https://user-images.githubusercontent.com/15989893/142493043-f5cf8d14-bd45-476f-a034-b13e4a9f64a8.png)

Changes have been pushed to show individual job parameters
![image](https://user-images.githubusercontent.com/2124590/143081216-542df6d8-afcb-4671-90cd-9fa09ad2fca6.png)

2021-11-23 18:16 UTC, sagar1312 commented on app/components/pipeline-event-row/component.js
> +    function numberOfParameters() {
Done

2021-11-23 18:16 UTC, sagar1312 commented
> For brand new pipelines, only shared parameters shows up, job level parameters does not show. ![image](https://user-images.githubusercontent.com/15989893/142493468-ead13c94-d90b-414b-817f-c58b6e231f9f.png)
> 
> It shows after kick off the 1st build.

Fixed

2021-11-29 17:30 UTC, adong submitted a review, later dismissed
Looks good to me. We can come back to visit this, if there's anything I overlooked,

2021-11-29 19:46 UTC, adong approved these changes

2021-11-30 01:31 UTC, merged