Alias column for the pipeline name
screwdriver-cd/ui pull request #790
Opened 2022-06-01 18:29 UTC by banusha2

## Context
 Added a column alias for renaming of the pipeline by the admin in preferred names which fits their pipeline.
            
## Objective
 To add a alias column for the pipeline rename

## References
Related to https://jira.ouryahoo.com/browse/SCREWDRV-10470
## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-07-20 16:01 UTC, adong commented
I checked out the branch before, can you attach screenshots for others?
Though it should ideally be something more than a text field, like a confirmation button, for now, that should be fine. 


Please add tests.

2022-07-20 16:03 UTC, adong commented on app/components/collection-table-row/component.js
> +    const aliasName = this.pipeline.settings?.aliasName;
Kudos for using `?.`!

2022-07-20 16:04 UTC, adong commented on app/components/collection-table-row/component.js
> +    return aliasName || name;
Hmm, please use `getWithDefault('aliasName', name);` over `||`

2022-07-20 16:04 UTC, adong commented on app/components/collection-table-row/component.js
> +    return aliasName || name;
For your reference, [getWithDefault](https://api.emberjs.com/ember/3.15/functions/@ember%2Fobject/getWithDefault)

2022-07-20 16:06 UTC, adong commented on app/components/collection-table-row/template.hbs
> +<td class="alias">
Hmm, its better to check if `alias` column is needed, if this collection dashboard does not have any pipeline that has alias feature, then we don't need to show the alias column, at least the current way is showing pipeline `name` again if `aliasName` is not set. I consider it is too much duplicate info

2022-07-20 16:06 UTC, adong commented on app/components/collection-view/template.hbs
> +              <th class="alias" rowspan="1">Alias</th>
Hmm, its better to check if alias column is needed, if this collection dashboard does not have any pipeline that has alias feature, then we don't need to show the alias column, at least the current way is showing pipeline name again if aliasName is not set. I consider it is too much duplicate info

2022-07-20 16:12 UTC, adong commented on app/components/pipeline-options/component.js
> +      let aliasName = inputPipelinAlias;
Typo

2022-07-20 16:14 UTC, adong commented on app/pipeline/events/route.js
> +      aliasName: getWithDefault(this.pipeline, 'settings.aliasName', 'appId')
What is `appId`? Was it put here accidentally for debugging? Please avoid magic string

2022-07-20 16:15 UTC, adong requested changes
Please make changes according to PR comments

2022-07-20 17:38 UTC, banusha2 commented on app/components/collection-table-row/component.js
> +    return aliasName || name;
`getWithDefault` because for some pipeline aliasName field doesn't exists. and I think getWithDefault checks if field is falsy if yes then return the alternate. but I have fixed the logic from `| |` to ternary operator. I used this before Idk what overwritten that with `| |`

2022-07-21 00:36 UTC, adong commented on app/components/collection-table-row/component.js
> +    return aliasName || name;
The ternary operator is worse than `||` in my opinion.  And I'm not talking about that, I genuinely think there's a better way of writing it. 

Let me give you one example. 

From
```javascript
    const aliasName = this.pipeline.settings?.aliasName;
    const { name } = this.pipeline.scmRepo;

    return aliasName || name;
```
To
```javascript
    const { name } = this.pipeline.scmRepo;

	return getWithDefault(this.pipeline.settings, 'aliasName', name);
```

2022-07-21 16:41 UTC, banusha2 commented on app/components/collection-table-row/component.js
> +    return aliasName || name;
I tried exactly same what you are suggesting and it gave error below. And I think that's because `aliasName` field does not exists for all the pipeline. 

<img width="1118" alt="Screen Shot 2022-07-21 at 11 36 44 AM" src="https://user-images.githubusercontent.com/104225232/180267657-e931c149-f7b4-473f-8ade-ca01da905f48.png">

2022-07-21 18:06 UTC, adong commented on app/components/collection-table-row/component.js
> +    return aliasName || name;
I just merged the latest master to this branch, I believe this issue would go away. 

`app/pipeline/model.js` already had default value for `pipeline.settings`. 
```
  settings: DS.attr({
    defaultValue() {
      return {
        groupedEvents: true,
        showEventTriggers: false
      };
    }
  }),
```

Particularly this change on `app/collection/model.js` by PR: https://github.com/screwdriver-cd/ui/pull/787, should fix it by establishing the relationship between collection to pipeline

```diff
export default DS.Model.extend({
  name: DS.attr('string'),
  description: DS.attr('string'),
  type: DS.attr('string'),
  pipelineIds: DS.attr(),
--  pipelines: DS.attr(),
++  pipelines: DS.hasMany('pipeline', { sync: true })
});
```


Test link: https://cd.screwdriver.cd/dashboards/4501

2022-07-22 15:06 UTC, banusha2 commented on app/components/collection-table-row/component.js
> +    return aliasName || name;
yeah that helped. Thanks

2022-07-22 16:21 UTC, banusha2 commented on app/components/collection-view/template.hbs
> +              <th class="alias" rowspan="1">Alias</th>
We can hide it for collection where not a single pipeline have a aliasname if admin add's aliasName to single pipeline. Then we will again have duplicate data. 
How about keeping it empty string by default instead of pipeline name?

2022-07-25 19:04 UTC, banusha2 commented
### added ellipsis and tooltip when hovering over aliasName
<img width="1024" alt="Screen Shot 2022-07-25 at 1 46 58 PM" src="https://user-images.githubusercontent.com/104225232/180854041-d01232b7-f429-4134-a364-9d239f6a15b8.png">

### hide aliasName coloumn if not a single pipeline in collection has a aliasName. 
<img width="1012" alt="Screen Shot 2022-07-25 at 1 50 43 PM" src="https://user-images.githubusercontent.com/104225232/180854057-64282c93-f46e-435f-960f-5fd9bc9faae1.png">

2022-07-25 19:25 UTC, adong commented on app/components/collection-view/component.js
> +  isAliasName: computed('collection.pipelines', {
Cool, can we change from `isAliasName` to `hasAliasName` for this boolean?

2022-07-25 19:29 UTC, adong commented on app/components/collection-view/component.js
> +      this.sortedPipelines.forEach(element => {
I think I know what this logics trying to do, 

1) The boolean value here will be overridden and totally depends on the last element of the array. If the last element array does not have `aliasName` even though the previous one has, then this boolean becomes `false`. Which is undesired. 

2) Instead of `forEach` use `[some](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some]` for array. I think that ought to cover that case.

2022-07-25 19:30 UTC, adong requested changes
Add more PR comments

2022-07-25 19:41 UTC, adong commented on app/components/collection-view/component.js
> +      this.sortedPipelines.forEach(element => {
3) Instead of using `sortedPipelines`, can we use `collectionPipelines`? Because the `sortedPipelines` like the name suggests, should update when sorting criteria changes `sortedPipelines: sort('collectionPipelines', 'sortBy'),
`, while `collectionPipelines` should remain unchanged. So using `collectionPipelines` will have less property change, and is more efficient.

2022-07-26 16:04 UTC, banusha2 commented on app/components/collection-view/component.js
> +      this.sortedPipelines.forEach(element => {
yeah, changed to `some`

2022-07-26 16:24 UTC, adong commented on app/components/pipeline-options/component.js
> +      pipeline.set('settings.aliasName', aliasName);
Hmm, I dont think `pipeline.set('settings.aliasName', aliasName);`, is not needed, otherwise we never know if it was set thru api or this line.

2022-07-26 16:25 UTC, adong commented on app/components/collection-view/component.js
> +      let isAliasName = this.collectionPipelines
Please change the name `isAliasName` to `hasAliasName`, it would make easier to read.

2022-07-26 16:32 UTC, adong commented on app/components/pipeline-options/template.hbs
> +              <p>Setup your own preferred pipeline name to display in the pipeline list.</p>
"...in the dashboard list view."

cc @tkyi see there's need to update the wordings

2022-07-26 16:32 UTC, adong commented on tests/integration/components/pipeline-options/component-test.js
> +        'Setup your own preferred pipeline name to display in the pipeline list.'
"...in the dashboard list view."

2022-07-26 16:48 UTC, adong commented on tests/integration/components/pipeline-options/component-test.js
> +    assert.dom('section.preference li:nth-of-type(4) input').hasText('test-pr');
Change from `hasText` to `hasValue` should work

2022-07-26 16:49 UTC, adong requested changes
More PR comments

2022-07-28 16:10 UTC, adong approved these changes
LGTM

2022-07-28 16:10 UTC, merged