fix: Move job name length user settings
screwdriver-cd/ui pull request #822
Opened 2022-09-06 17:14 UTC by banusha2

## Context

To display JobName length in User Settings.

## Objective
<img width="976" alt="Screen Shot 2022-09-06 at 1 02 50 PM" src="https://user-images.githubusercontent.com/104225232/188698537-aaa74a6b-996c-4d68-b831-ce408bd463aa.png">

## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-09-06 17:38 UTC, adong commented on app/components/user-setting/component.js
> +        await this.shuttle.deleteUserSettings();
Can you implement it in the [`deleteRecord`](https://api.emberjs.com/ember-data/3.16/classes/Store/methods/deleteRecord?anchor=deleteRecord)
See 
https://github.com/screwdriver-cd/ui/blob/master/app/preference/pipeline/adapter.js#L21

as refererence

2022-09-06 17:44 UTC, adong commented on app/components/user-setting/component.js
> +        await this.shuttle.deleteUserSettings();
This way, the records in the ember data store will be in sync.

2022-09-06 17:57 UTC, adong commented on app/components/user-setting/style.scss
> +  .saving-loading {
Can we handle the show & hide logic in the `template.hbs`? It is not easy to debug if logics are handled in CSS.

2022-09-06 17:59 UTC, adong commented on app/user-settings/preferences/template.hbs
> +{{user-setting}}
I have some reservations of converting the code into a `component`, because component will be re-render each time we enter this route (which will  make API to fetch the user preference everytime), while controller's `template.hbs` will only render once (since the controller is a singleton)

2022-09-06 19:37 UTC, adong commented on app/components/user-setting/component.js
> +        await this.shuttle.deleteUserSettings();
And it's easier to add tests too.

- https://github.com/screwdriver-cd/ui/blob/master/tests/unit/preference/user/serializer-test.js#L57
- https://github.com/screwdriver-cd/ui/blob/master/tests/unit/shuttle/service-test.js

2022-09-07 15:24 UTC, banusha2 commented on app/user-settings/preferences/template.hbs
> +{{user-setting}}
I thought that in future if we want to add few more sections in user preferences it will be easy to do so. And adding css to route level `template.hbs`, can break other css with same classnames. I am not sure on this. what do you think?

2022-09-07 15:24 UTC, banusha2 commented on app/components/user-setting/style.scss
> +  .saving-loading {
ok will do it.

2022-09-07 19:21 UTC, adong commented on app/user-settings/preferences/template.hbs
> +{{user-setting}}
Conceptionally, if some code would be re-used, then we make it into a component. 
For example, the access-token component is being used in multiple places. One here, and another one used in `pipeline -> options -> access`

2022-09-07 19:21 UTC, adong commented on app/user-settings/preferences/template.hbs
> +{{user-setting}}
Could this component be re-named to say, `user-preference` instead of `user-setting`?

2022-09-08 14:06 UTC, banusha2 commented on app/user-settings/preferences/template.hbs
> +{{user-setting}}
Okay, so should i move the code in component to `preference/template.hbs`

2022-09-08 16:41 UTC, adong commented on app/user-settings/preferences/template.hbs
> +{{user-setting}}
Actually, I thought about and tested out, I still prefer to see it in the `app/user-settings/preferences/controller.js` controller, see reasons in https://github.com/screwdriver-cd/ui/pull/822/files#r966186063

2022-09-08 16:45 UTC, banusha2 commented on app/components/user-preference/component.js
> +    this.set('isSaving', true);
oh got it, shifting code to controller's `template.hbs`

2022-09-08 16:48 UTC, adong commented on app/shuttle/service.js
> +      settings: {}
I also felt the payload `data = {settings: {}}` code is not necessary according to the backend, which does not take the payload.

https://github.com/screwdriver-cd/screwdriver/pull/2762/files#diff-ff0d529733cb812e0466575567bf1fee2f488a9dfc27fafdba520ffacb3a9a7aR26

2022-09-08 16:49 UTC, adong commented on app/shuttle/service.js
> +      settings: {}
You can remove data, and just call `this.fetchFromApi(method, url)`, I think the `fetchFromApi(method, url)` will add a default value for `data`, which is `{}`

2022-09-08 18:44 UTC, adong commented on app/components/user-preference/component.js
> +    this.setProperties({ desiredJobNameLength });
Need to store `userSettings` here in `init` function, so in `updateUserSettings` and `resetUserSettings`, you can just use `this.userSettings` without call `const userSetting = await this.userSettings.getUserPreference();`

2022-09-08 18:45 UTC, adong commented on app/components/user-preference/component.js
> +        await this.store.deleteRecord('preference/user');
Need to change to await `this.store.deleteRecord(this.userSetting)`, assuming this property is saved in `init` https://github.com/screwdriver-cd/ui/pull/822/files#r966309833

2022-09-08 18:45 UTC, adong commented on app/components/user-preference/style.scss
> +& {
Please refactor this back to a controller.

2022-09-08 18:47 UTC, adong requested changes
See comments.

2022-09-12 15:56 UTC, adong commented on app/user-settings/preferences/controller.js
> +    const userSetting = await this.userSettings.getUserPreference();
Can we rename `userSetting` to `userSettings` just for the consistency's sake, since it is `this.userSettings`?

2022-09-12 15:57 UTC, adong commented on app/user-settings/preferences/controller.js
> +    }
Can you refactor 
```
this.setProperties({
        isSaving: false,
```

To `finally` block with `this.set('isSaving', false);`?

2022-09-12 15:57 UTC, adong commented on app/user-settings/preferences/controller.js
> +        });
same here, add a finally block and for `this.set('isSaving', false);`

2022-09-12 16:03 UTC, adong commented on app/user-settings/preferences/controller.js
> +    const userSetting = await this.userSettings.getUserPreference();
Actually, it should not be called `userSetting` nor `userSettings`, rather than `userPreference`

2022-09-13 17:37 UTC, adong commented
This PR needs to wait until https://github.com/screwdriver-cd/screwdriver/pull/2762/files merged

2022-09-13 17:41 UTC, adong commented on app/styles/user-settings.scss
> +  .saving-loading {
Deja vu, I thought I commented on this before. 🤔 

Anyway, please handle the show/hide logics in `template.hbs` rather than css, css is not easy to debug.

2022-09-13 17:41 UTC, adong commented on app/styles/user-settings.scss
> +      display: none;
Similar here

2022-09-13 17:42 UTC, adong commented on app/user-settings/preferences/template.hbs
> +              <div class="saving-loading">
`if/else` in js over `display: none;` in css.

2022-09-14 14:09 UTC, banusha2 commented on app/styles/user-settings.scss
> +  .saving-loading {
Fixed

2022-09-14 14:09 UTC, banusha2 commented on app/styles/user-settings.scss
> +      display: none;
fixed

2022-09-14 14:09 UTC, banusha2 commented on app/user-settings/preferences/template.hbs
> +              <div class="saving-loading">
Got it. I have fixed it now

2022-09-19 16:00 UTC, adong commented on app/user-settings/preferences/controller.js
> +    this.setProperties({ desiredJobNameLength, userPreferences });
Please add initialization of `successMessage, errorMessage, isSaving, isValid` properties in the init() function

2022-09-19 16:00 UTC, adong requested changes
Please add tests, otherwise, looks good to me.

2022-09-19 16:06 UTC, adong commented on app/user-settings/preferences/controller.js
> +        await this.store.deleteRecord(this.userPreferences);
I dont think `deleteRecord` returns a promise, so no await is needed for this one. Just needs to await on the `save()`
See https://github.com/emberjs/data/blob/v4.6.1/packages/model/addon/-private/model.js#L671

2022-09-21 02:05 UTC, adong approved these changes
LGTM

2022-09-21 02:05 UTC, merged