feat: Add timestamp options in user preferences
screwdriver-cd/ui pull request #823
Opened 2022-09-14 13:53 UTC by banusha2

## Context
When user looks at events, getting several events happened "2 months ago." When looking  at the list view, confused with timestamp such as "August 18, 2020 4:52 PM."

## Objective
To add Timestamp options in user preferences -UTC Timestamp, Local Timestamp.

## References

https://github.com/screwdriver-cd/screwdriver/issues/2218

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-09-23 15:59 UTC, adong commented on app/user-settings/preferences/controller.js
> +        await this.userPreferences.save();
I was going to comment, but realized this file might be out dated, because `unload` is missing.

2022-09-23 16:01 UTC, adong commented on app/user-settings/preferences/controller.js
> +    let selectedTimestampFormat = this.timestampOptions.find(
If we are hard coding to be `LOCAL_TIMEZONE`, then this could be written as `this.timestampOptions[1]`, or `this.get('timestampOptions', 'lastObject');` latter seems to be more elegant, but they are the same thing essentially.

2022-09-27 17:31 UTC, adong commented on app/user-settings/service.js
> +    let desiredTimestampFormat = 'LOCAL_TIMEZONE';
Hmm, this actually is the part that makes what the default value is for timestamp format. Can we not hard code the `LOCAL_TIMEZONE` string?  There has to be a better way. I need to think about it.

2022-09-27 17:32 UTC, adong commented on app/user-settings/preferences/controller.js
> +  timestampOptions: [
I would make this into model.js, see other comments

2022-09-27 17:40 UTC, adong commented on app/preference/user/model.js
> +  @attr('string') timestampFormat;
This should have a default value, say

```
export const TIMESTAMP_OPTIONS = ['option1', 'option2'];
export const TIMESTAMP_DEFAULT_OPTION = 0;
...
  @attr('string', { defaultValue:  TIMESTAMP_OPTIONS[TIMESTAMP_DEFAULT_OPTION] }) timestampFormat;
```

So, other classes can import it, like `app/user-settings/service.js` can re-use it without dictating the default timezone value, and we have a central place to adjust what the default timezone value is.

2022-09-27 17:42 UTC, adong commented on app/user-settings/preferences/controller.js
> +  timestampOptions: [
Actually, I don't have a strong feeling about list these `timestampOptions` here, I just think we should keep `app/user-settings/service.js` away from hard-coding default values.

2022-09-29 16:00 UTC, adong commented on app/user-settings/preferences/controller.js
> +    let selectedTimestampFormat = this.get('timestampOptions', 'lastObject');
Hmm, I get what this trying to do, but the syntax is not correct.
![image](https://user-images.githubusercontent.com/15989893/193080802-2d9a46b0-80ce-44fc-91fe-0d393f02f30b.png)


Besides, since `TIMESTAMP_DEFAULT_OPTION` is `0`, and `lastObject` usually isn't `0`. So this can be replaced with `firstObject`. 
```
this.get(`timestampOptions.firstObject`);
```

If really wants to make it modular, it ought to be

```
this.get(`timestampOptions.${TIMESTAMP_DEFAULT_OPTION}`)
```

I prefer this one ☝️

![image](https://user-images.githubusercontent.com/15989893/193080885-a7056278-b9c4-4b2d-bd67-db78c5c0f3c5.png)

2022-09-29 16:07 UTC, adong commented on app/utils/timestamp-format.js
> +  { key: 'UTC', name: 'UTC' }
Why is the variable inside the object called `key`, is it used in other 3rd party conventions? If it's not required, please change it to `value`, because `key` was confusing.

2022-09-29 16:09 UTC, adong commented on app/preference/user/model.js
> +    defaultValue: TIMESTAMP_OPTIONS[TIMESTAMP_DEFAULT_OPTION].key
This is the part that confused me, assign key to defaut`Value`. I believe `value` is more appropriate and easy to read.
```diff
--defaultValue: TIMESTAMP_OPTIONS[TIMESTAMP_DEFAULT_OPTION].key
++defaultValue: TIMESTAMP_OPTIONS[TIMESTAMP_DEFAULT_OPTION].value
```

2022-09-29 16:28 UTC, adong commented
For this particular PR, I only see pipeline list view show different timestamp formats, per https://github.com/screwdriver-cd/screwdriver/issues/2218 request, I think the user wants to see the event list view to have utc/local time zone

![image](https://user-images.githubusercontent.com/15989893/193087029-9c00993e-f799-4859-99b2-2100ea65e5f6.png)

2022-09-29 16:32 UTC, adong requested changes

2022-09-29 16:32 UTC, adong commented on app/user-settings/preferences/controller.js
> +    let selectedTimestampFormat = this.get('timestampOptions', 'lastObject');
Somehow the test case didn't catch it. I guess either the test was either:

1) `selectedTimestampFormat` got overridden by `userPreference`'s timestamp
2) there's no test case was covering the `userPreference` is falsy case.


_Please test more thoroughly._

2022-09-30 12:57 UTC, banusha2 commented on app/utils/timestamp-format.js
> +  { key: 'UTC', name: 'UTC' }
Changed

2022-09-30 12:57 UTC, banusha2 commented on app/user-settings/preferences/controller.js
> +    let selectedTimestampFormat = this.get('timestampOptions', 'lastObject');
sure adding more tests

2022-09-30 16:18 UTC, adong commented on app/components/pipeline-event-row/component.js
> +    const userPreferences = this.store.peekAll('preference/user');
The `userPreference` would be empty if `preference/user` does not load before viewing this page, so, better user 
```
const userPreference = await this.getUserPreference();
```

which handles that gracefully in the userSetting service.

2022-09-30 16:19 UTC, adong commented on app/components/pipeline-graph-nav/component.js
> +    const userPreferences = this.store.peekAll('preference/user');
Same thing here.

```
const userPreference = await this.getUserPreference();
```



Another comment is, these two code blocks are very similar, wonder if there's a way to DRY it.

2022-09-30 16:23 UTC, adong commented
Can you add tests for
1) event-list page with 
	* Local timezone and
	* UTC
2) pipeline-graph-nav
	* Local timezone and
	* UTC
3) job list view
	* Local timezone and
	* UTC

2022-09-30 16:25 UTC, adong commented on app/components/pipeline-event-row/component.js
> +      const timestampPreference = get(
```
const userPreference = await this.getUserPreference();
```

2022-10-03 19:59 UTC, jithine commented on app/components/pipeline-event-row/component.js
> +          const timestampPreference = get(userPreference, 'timestampFormat');
this code block is a good candidate for a helper function. perhaps here https://github.com/screwdriver-cd/ui/blob/master/app/utils/time-range.js
 I see this chunk of code repeated frequently

2022-10-04 15:53 UTC, banusha2 commented on app/components/pipeline-event-row/component.js
> +          const timestampPreference = get(userPreference, 'timestampFormat');
Yes,  done

2022-10-11 17:16 UTC, tkyi commented on app/utils/timestamp-format.js
> + * @param {string} startDate input date
```suggestion
 * @param {Object} userSettings  User settings
 * @param {String} startDate         Input date
```

2022-10-11 17:18 UTC, tkyi commented on app/user-settings/service.js
> +    let desiredTimestampFormat;
should you set a default?

2022-10-14 06:53 UTC, banusha2 commented on app/user-settings/service.js
> +    let desiredTimestampFormat;
Default is set in model. in our one discussion Alan said that its not good to have hard coded data in services.

2022-10-14 17:55 UTC, tkyi commented on app/components/pipeline-graph-nav/template.hbs
> +          <span>{{startDate.content}}</span>
just wondering, what is `content`? why can't we just use `startDate` directly?

2022-10-17 15:28 UTC, banusha2 commented on app/components/pipeline-graph-nav/template.hbs
> +          <span>{{startDate.content}}</span>
using `async` `await` in get function was not working as expected, page gets rendered first and data is computed after that. so we used `ObjectPromiseProxy` and it returns an object and our computed data is in `content` hence `startDate.content`

2022-10-17 18:22 UTC, merged