fix: Change aliasname default to ''
screwdriver-cd/ui pull request #828
Opened 2022-09-21 21:05 UTC by banusha2

## Context

Once any pipeline's aliasName is set in a collection, that collection shows pipeline's aliasName for all pipeline, which isn't ideal.

## Objective

Display pipeline's aliasName ,if an aliasName is set .
<img width="987" alt="Screen Shot 2022-09-21 at 11 29 21 AM" src="https://user-images.githubusercontent.com/104225232/191546861-e6e5bad8-2825-49fc-8019-ae407a3759bf.png">

## References
https://github.com/screwdriver-cd/screwdriver/issues/2765

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-09-21 21:08 UTC, jithine submitted a review, later dismissed

2022-09-21 21:41 UTC, adong requested changes
Can you add a test? I’m actually a little surprised that the test case didn’t catch alias/name changes.

2022-09-22 15:05 UTC, banusha2 commented
> Can you add a test? I’m actually a little surprised that the test case didn’t catch alias/name changes.

I fixed the test cases in that PR as I remember.

2022-09-22 15:52 UTC, adong commented
> > Can you add a test? I’m actually a little surprised that the test case didn’t catch alias/name changes.
> 
> I fixed the test cases in that PR as I remember.

Hmm, I'm saying there should 2 tests that

1) has only pipeline name without alias
2) has both alias and name

So, later on, if either one behavior changes, we can catch it in the tests

2022-09-22 20:20 UTC, adong requested changes

2022-09-22 20:20 UTC, adong commented on tests/integration/components/collection-view/component-test.js
> +      .hasText('screwdriver-cd/zzz');
```
assert.dom('.collection-pipeline:nth-of-type(4) .app-id p').hasText('zzz');
```
Is not sufficient, because `screwdriver-cd/zzz` also has `zzz`

I would say, add another check that ensures:
```
      .hasText('zzz');
```
And
```
      . doesNotIncludeText('screwdriver-cd/zzz');
```
see: https://github.com/simplabs/qunit-dom/blob/master/lib/__tests__/does-not-include-text.ts

2022-09-22 21:40 UTC, adong commented on tests/integration/components/collection-view/component-test.js
> +      .hasText('screwdriver-cd/zzz');
These comments should go to previous code block, https://github.com/screwdriver-cd/ui/pull/828/files/007392b2ee221f2c4b0a55e3dc91b611e9520808#diff-1d40fc3763f6a0d8c53bccb59972eb04fc0386972af290e245f57918576cb977R668

2022-09-23 21:07 UTC, adong approved these changes

2022-09-23 21:07 UTC, adong commented on tests/integration/components/collection-view/component-test.js
> +      .doesNotIncludeText('screwdriver-cd/zzz');
LGTM

2022-09-23 21:07 UTC, merged