feat: Add sorting on alias/name column
screwdriver-cd/ui pull request #830
Opened 2022-09-28 14:30 UTC by banusha2

## Context
To add sorting on alias/name column in Dashboard.

## Objective
1.Sort based on alias if pipeline has alias, in alphabetical order.
2.Sort based on pipeline name if alias not exist, in alphabetical order.

## References
https://github.com/screwdriver-cd/screwdriver/issues/2765

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-09-28 17:39 UTC, adong requested changes

2022-09-28 17:39 UTC, adong commented on app/components/collection-view/template.hbs
> +              <th class="app-id" onclick={{action "setSortBy" (if (eq (get sortBy 0) (if pipeline.settings.aliasName "pipeline.settings.aliasName:desc" "scmRepo.name:desc")) (if pipeline.settings.ali
Wow, this logic probably is correct and confusing. how about convert all 

```
(if (eq (get sortBy 0) (if pipeline.settings.aliasName "pipeline.settings.aliasName:desc" "scmRepo.name:desc")) (if pipeline.settings.aliasName "pipeline.settings.aliasName:asc" "scmRepo.name:asc") (if pipeline.settings.aliasName "pipeline.settings.aliasName:desc" "scmRepo.name:desc"))}
```

these to a computed property, as

```
onclick={{action "setSortBy" aliasName}}

aliasName: computed('pipeline.settings.aliasName',  'scmRepo.name', 'sortBy') {
	const sortingCriteria = '';
	if () {
   sortingCriteria = 'xx';
  } else {
    sortingCriteria = 'yy'
  }
  return sortingCriteria;
}

```

2022-09-29 16:39 UTC, adong commented on app/components/collection-view/component.js
> +          this.sortBy[0] === 'pipeline.settings.aliasName:desc'
Can we use plain if else, and not use ternary operator `?` ?

2022-09-29 16:48 UTC, adong commented
Also please add test cases, pipeline collection dashboard with: 

1) pipeline (without alias) default list
1) pipeline (without alias) list ascending order
1) pipeline (without alias) list descending order

1) pipeline (with alias) default list
1) pipeline (with alias) sorted list ascending order
1) pipeline (with alias) sorted list descending order

There may be a duplicate between 1) & 4), since default sorting criteria would be the same, and based on added time (if I recall correctly), still I list all possible scenarios I can think of.

2022-11-11 08:22 UTC, jithine approved these changes

2022-11-30 19:38 UTC, tkyi commented
Still missing test cases listed here: https://github.com/screwdriver-cd/ui/pull/830#issuecomment-1262542043

2022-12-06 17:11 UTC, banusha2 commented
Feature will be served using PR #855

2022-12-06 17:11 UTC, closed without merging