fix: Correct data in last run job column
screwdriver-cd/ui pull request #834
Opened 2022-10-06 20:17 UTC by banusha2

## Context
Last run job column's data is not correct.

## Objective
Display correct data in Last run job column in collection.

## References
https://github.com/screwdriver-cd/screwdriver/issues/2765

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-10-12 15:42 UTC, jithine commented on app/components/collection-table-row/component.js
> +      promise: this.pipeline.get('metrics').then(metrics => {
does this cause extra API calls ?

2022-10-12 16:08 UTC, jithine reviewed
don't we already have lastEventInfo, why is this needed

2022-10-12 16:17 UTC, banusha2 commented
> don't we already have lastEventInfo, why is this needed

lastEventInfo don't have the createTime information. and afaik event and job are different things

2022-10-12 16:20 UTC, banusha2 commented on app/components/collection-table-row/component.js
> +      promise: this.pipeline.get('metrics').then(metrics => {
No it just gets data from already fetched model. We have to treat it like a promise because Ui gets rendered before we compute the data and ui breaks

2022-10-14 20:48 UTC, jithine commented
@banusha2 last run event's data is good enough. Both should be more or less matching. Infact you brought an important point. Column should not be about last run job, it should be event. 
I propose to remove `job` from the column name, and just call it  `Last Run`

2022-10-19 20:08 UTC, jithine requested changes
see my last comment, it should be last run event's info, not job's.

2022-10-25 14:25 UTC, banusha2 commented
> see my last comment, it should be last run event's info, not job's.

Yes I have made changes please have look again

2022-10-26 18:31 UTC, jithine requested changes
1. get rid of `last run` stuff in this PR and  rename `start date` to `last run`
2. same change in card view also
3. in card view have `last run` first before the `duration` in the row. you will understand once you see the view

2022-10-27 16:13 UTC, banusha2 commented on app/pipeline/model.js
> +  lastRunEvent: computed('metrics.[]', {
yes, but we need it in collection-view component for sorting feature.

2022-10-27 19:03 UTC, jithine approved these changes

2022-10-27 19:03 UTC, merged