Fix: status sorting logic
screwdriver-cd/ui pull request #855
Opened 2022-11-15 16:19 UTC by banusha2

## Context

sorting on status column.
## Objective

To sort status column based on priority sort.
## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-11-18 17:38 UTC, adong commented on app/components/collection-view/component.js
> +        'ABORTED' : 6,
This is an eye sore, can you reorder it in asc / desc order?

2022-11-18 17:39 UTC, adong commented on app/components/collection-view/component.js
> +        'ABORTED' : 6,
Also what if the status passed in was not defined?

2022-11-21 16:53 UTC, adong requested changes

2022-11-21 16:53 UTC, adong commented on app/components/collection-view/component.js
> +      this.set('sortedPipelines', newSortedPipelines);
Hmm, `sortedPipelines: sort('collectionPipelines', 'sortBy'),` see https://github.com/screwdriver-cd/ui/pull/855/files#diff-454c2200cdb1986fe26070e9113b98f9523bf68bdf5a35c3a96155a9b0549884R103


is a computed property, by doing so, it will break other sorting criteria, since this property is no longer a computed property, and will not react and update if dependent properties change

2022-11-22 18:53 UTC, adong reviewed
Change `sort` to `computed` to debug:  

Old
```
  sortedPipelines: sort('collectionPipelines', 'sortBy'),
```
New
```
  sortedPipelines: computed('collectionPipelines', 'sortBy', function() {
   // console what sortBy is, see if it expected
 }),
```

To debug what `sortBy` value is, and see why after `lastRunEvent.status:asc` and `lastRunEvent.status:desc` are set, and didn't work as expected.


PS: 
I have suspect something related to 

```
app/pipeline/model.js
79:  lastRunEvent: computed('metrics.[]', { 
```

If neither worked, we can sort the old way.

2022-11-29 18:44 UTC, adong commented on app/components/collection-view/component.js
> +      sorted = this.collectionPipelines.toArray().sort((a,b) => {
2 comments. 

1) Extract these `sort(a, b)` functions to the top of the file, so it would be easier to modify and test individually without mocking the whole thing. 

2) Another comment on this, does it work on all column sorts? I see right now, only 2 columns are supported, i.e. `lastRun` and `scmRepo.name`

2022-11-29 18:44 UTC, adong commented on app/components/collection-view/component.js
> +     return sorted;
Minor comment: indention

2022-11-29 18:48 UTC, adong commented on app/components/collection-view/component.js
> +      sorted = this.collectionPipelines.toArray().sort((a,b) => {
Here's what I mean:

```
const sortByLastRunStatus = function(a, b) { // logics }
const sortByRepoName =  function(a, b) { // logics }
```

Then use as

```
if (this.sortBy === 'lastRun') {
  sorted = this.collectionPipelines.toArray().sort(sortByLastRunStatus)
}

```

2022-11-29 20:05 UTC, banusha2 commented on app/components/collection-view/component.js
> +      sorted = this.collectionPipelines.toArray().sort((a,b) => {
No, it doesn't work on all the columns.we have to fix all other column as well.

2022-11-30 22:50 UTC, adong commented on app/components/collection-view/component.js
> +    } else if(this.sortBy === 'scmRepo.name') {
Please refactor this `this.collectionPipelines.toArray()` to be a variable beforehand.

2022-12-05 15:09 UTC, banusha2 commented on app/components/collection-view/component.js
> +    } else if(this.sortBy === 'scmRepo.name') {
Ok

2022-12-06 18:27 UTC, adong commented on app/components/collection-view/component.js
> +          this.setProperties({
Question, do we need these
```
switch ()
 ...
```

Anymore? If not, please delete these lines. Just keep

```
          this.setProperties({
            sortBy: option,
            sortOrder: order
          });
```

2022-12-09 18:36 UTC, adong requested changes

2022-12-09 18:36 UTC, adong commented on app/components/collection-view/component.js
> +const sortByLastRunStatus = (a, b) => {
Please use `export const`, and add tests for these sorting functions

2022-12-13 18:19 UTC, adong commented on tests/unit/utils/sort-functions-test.js
> +  test('it sorts pipelines based upon names', function (assert) {
Can you add to the description that the sorting is specific in either ascending or descending order, so it's easier to understand?

2022-12-13 18:54 UTC, adong commented on tests/unit/utils/sort-functions-test.js
> +  test('it sorts pipelines based upon names', function (assert) {
Hmm, on second thought, lets leave as is for now

2022-12-13 18:54 UTC, adong approved these changes

2022-12-13 18:55 UTC, merged