fix: make links clickable
screwdriver-cd/ui pull request #872
Opened 2022-12-21 17:39 UTC by banusha2

## Context
To set hyperlink to 'label' like 'commit' field.

## Objective
users don’t have to look for info in the log ,simply click and go.

## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-12-21 17:51 UTC, adong commented on app/components/pipeline-graph-nav/component.js
> +      label = label.replace(/(https?\/\/[^\s+])/g, '<a href="$1">$1</a>');
I would refactor this logic to a utility function called, does the text contain hyperlinks, `isTextLinkable`, and another function like `TransformTextToClickableContent`, something like that.

Also this logic only detects and replaces the first url, I think.

2022-12-21 17:56 UTC, adong commented on app/components/pipeline-graph-nav/component.js
> +      label = label.replace(/(https?\/\/[^\s+])/g, '<a href="$1">$1</a>');
Please refer this: 
https://www.cluemediator.com/find-urls-in-string-and-make-a-link-using-javascript

2022-12-21 18:05 UTC, adong commented on app/components/pipeline-graph-nav/component.js
> +      label = label.replace(/(https?\/\/[^\s+])/g, '<a href="$1">$1</a>');
😀 It turns out frequent enough to as an interview question, and solution is in-place. https://www.pcoroneos.com/cracking-the-code-interview-1-3-urlify

2022-12-22 17:32 UTC, adong commented on app/components/pipeline-graph-nav/component.js
> +      const isTextLinkable = DoesTextContainsLink(label);
`DoesTextContainsLink`,  `TransformTextToClickableContent` camel case please

Also, please refactor `isTextLinkable` to be a computed property and use in the template

2022-12-22 17:34 UTC, adong commented on app/components/pipeline-graph-nav/template.hbs
> -            <span class="customize-label" title={{selectedEventObj.label}}>{{selectedEventObj.label}}</span>
When `isTextLinkable` is a computed property of a boolean, 
Check if `isTextLinkable` true, then show `{{{label}}}`, otherwise, show `{{selectedEventObj.label}}`

2022-12-22 17:35 UTC, adong commented on app/utils/convert-url.js
> +  return new RegExp(URL_REGEX).test(text);
Can you rename this file to be `url-helper`, instead of convert url? `convert url` sounds like a function name and only convert url, rather than file name that contains all url related functions

2022-12-22 17:35 UTC, adong commented on app/utils/convert-url.js
> +export function TransformTextToClickableContent(text) {
camel case

2022-12-22 17:35 UTC, adong commented on app/utils/convert-url.js
> +export function DoesTextContainsLink(text) {
camel case

2022-12-22 17:53 UTC, adong commented on app/utils/convert-url.js
> +  return text.replace(URL_REGEX, function (url) {
After I think more about it, I suspect this logic has a potential issue for cross-site scripting. For example, what would be rendered in `{{{label}}}` if `text` contains both valid hyperlinks and malicious scripts? 

i.e.

```
this is my build, http://screwdriver.cd/build/112233, here's my script <script>alert('XSS')</script>
```

Just want to point out, the current implementation _would_ run into issues.

2022-12-22 17:54 UTC, adong commented on app/components/pipeline-graph-nav/template.hbs
> -            <span class="customize-label" title={{selectedEventObj.label}}>{{selectedEventObj.label}}</span>
`isTextLinkable` => `hasContainLinkableText`

2022-12-22 17:58 UTC, adong commented on app/utils/convert-url.js
> +  return text.replace(URL_REGEX, function (url) {
Hmm. Interestingly, github does something similar. 

![image](https://user-images.githubusercontent.com/15989893/209196960-77b8ca3e-bf44-4437-a44a-d1d4a9be9df7.png)

![image](https://user-images.githubusercontent.com/15989893/209196943-29be5ddb-36a8-4b2a-b4cc-57acdd3a09b2.png)

2022-12-22 18:04 UTC, adong commented on app/utils/convert-url.js
> +  return text.replace(URL_REGEX, function (url) {
Please check out

>  [Usage of triple curly braces to allow raw HTML to be injected into the DOM is a large vector for exploits of your application (especially when the raw HTML is user-controllable). Instead of using `{{{foo}}}`, you should use appropriate helpers or computed properties that return a `SafeString` (via `Ember.String.htmlSafe` generally) and ensure that user-supplied data is properly escaped.](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-triple-curlies.md)

and [htmlSafe](https://api.emberjs.com/ember/release/functions/@ember%2Ftemplate/htmlSafe) helper

2022-12-23 15:15 UTC, banusha2 commented on app/utils/convert-url.js
> +  return text.replace(URL_REGEX, function (url) {
yes done

2022-12-23 17:46 UTC, adong commented on app/utils/url-helper.js
> +    return (
Instead of a string concatenation, how about just returning [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) ?

2022-12-23 18:00 UTC, adong requested changes

2022-12-23 18:00 UTC, adong commented on app/utils/url-helper.js
> +  return text.replace(URL_REGEX, function transformUrl(url) {
As I mentioned before, this function needs to filter out only to allow links to be processed and filter anything else. 

See:

![image](https://user-images.githubusercontent.com/15989893/209385319-3fe0b727-1f3b-4503-bfa5-823b38273837.png)

And `https://cd.screwdriver.cd/pipelines/7290/events/718950?jobId=`
![image](https://user-images.githubusercontent.com/15989893/209385418-b4fc6999-3b62-4f9b-9611-1dc510e5be2a.png)

2022-12-27 16:59 UTC, banusha2 commented on app/utils/url-helper.js
> +  return text.replace(URL_REGEX, function transformUrl(url) {
Sorry I didn't get it. what we have to filter out.

2023-01-10 16:27 UTC, adong commented on tests/unit/utils/url-helper-test.js
> +  'Lorem ipsum dolor sit amet, <a href="https://abc.com" target="_blank" rel="noopener noreferrer">https://abc.com</a> consectetur adipiscing elit, sed do eiusmod tempor incididunt ut <a href="http:/
Try adding some script tag and image tag to check the functionalities for `transformTextToClickableContent`. I dont think it would work.

2023-01-10 16:30 UTC, adong requested changes
Hmm, I don't think the current implementation handles the XSS issue I brought up earlier. Can you implement a small XSS sanitizer file with an allow list to filter out the non-allowed tags?

In that case, the function `transformTextToClickableContent`'s transformation part can remain the same

2023-01-18 18:56 UTC, adong commented on app/utils/sanitize.js
> +  function sanitiseNode(node) {
1) Rename the file from `sanitize` to `sanitizer`
2) Please update the word `sanitise` to `sanitize` to for consistency's sake.

2023-01-18 19:06 UTC, adong commented on app/utils/url-helper.js
> +
Please put `const sanitizer = new Sanitizer();` here, outside export, otherwise, this Sanitizer gets initialized everytime `transformTextToClickableContent` gets called.

2023-01-18 19:20 UTC, adong commented on app/utils/url-helper.js
> +const URL_REGEX = /(((https?:\/\/)|(www\.))[^\s]+)/g;
This regex is not working properly. It will transform `https://x.com,abcdef` as well, which shouldn't.

2023-01-18 19:26 UTC, adong commented on app/components/pipeline-graph-nav/component.js
> +      let label = this.get('selectedEventObj.label');
Please rename this computed property from `label` to `linkableTextLabel`. 

`label` is confusing, because the code shows here is actually transformed, not raw label.

2023-01-18 19:44 UTC, adong commented on app/utils/url-helper.js
> +    if (!hyperlink.match('^https?://')) {
I don't think this code does what is intended to do. 

This code can be simplified as it assumes the `url` already has `http` or `https`, or `www`, this if statement only runs for url with `www` and prefix with `http://`. 


By the way, why sanitizer runs before regex replacement? I don't get the order of the logic here. We should be filtering at the end to make sure the final code aligns with allow/blocked tags.

2023-01-18 19:44 UTC, adong requested changes
Not working properly

2023-01-18 19:45 UTC, adong commented on tests/unit/utils/url-helper-test.js
> +module('Unit | Utility | url-helper', function () {
This is a good one _overall_ test case. Can you add more test cases to handle each scenario?

2023-01-19 16:04 UTC, banusha2 commented on app/utils/url-helper.js
> +    if (!hyperlink.match('^https?://')) {
because first sanitizer removes all the extra tags then which user has put link then that link is converted into a `<a>` tag.

2023-01-19 16:05 UTC, banusha2 commented on tests/unit/utils/url-helper-test.js
> +module('Unit | Utility | url-helper', function () {
sure

2023-01-20 16:19 UTC, banusha2 commented on app/utils/url-helper.js
> +    if (!hyperlink.match('^https?://')) {
Now sanitization is done at last. 

i didn't you get on second statement here.

2023-01-20 22:01 UTC, adong commented on app/utils/url-helper.js
> +    if (!hyperlink.match('^https?://')) {
Let me add more explanations. 

I'm saying the code block of 

```
if (!hyperlink.match('^https?://')) {  
...

```

Only converts url string starts with `www`, and will not work for other links like `yahoo.com`, will not work for `github.io`, or even `screwdriver.cd`. 

Coming up with our own regex is very unlikely to cover all possible urls. 

I need to think more about it, and there has to be a better way.

2023-01-23 20:01 UTC, adong commented
Actually, this PR became overly complicated for issue https://github.com/screwdriver-cd/screwdriver/issues/2805, and does not handle

Check out this library, https://github.com/johno/ember-linkify, which uses https://github.com/Hypercontext/linkifyjs under the hood, in my opinion, more industry-standard,  which handles 1) link detection and transformation and 2) the XSS Sanitization.  See [demo](https://linkify.js.org/#demo)

Try: 

`ember install ember-linkify`

Should be much easier 

File: `app/components/pipeline-graph-nav/template.hbs`

```
<span class="customize-label" title={{selectedEventObj.label}}>{{linkify selectedEventObj.label urlLength=30}}</span>
```

Thus, I'm closing this PR, please raise a new PR.

2023-01-23 20:01 UTC, closed without merging