Sagar1312 feat 2669 pipeline stages
screwdriver-cd/ui pull request #873
Opened 2023-01-03 18:22 UTC by sagar1312

## Context

Render Stages in the workflow graph if configured

## Objective

Render Stages in the workflow graph if configured

## References

https://github.com/screwdriver-cd/screwdriver/issues/2669

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-01-10 17:06 UTC, adong commented
I tried a sample PR: 
https://cd.screwdriver.cd/pipelines/9762/events/704140

The `Y_DISPLAYMENT` on row1 and row2 are good, and on row3 is not.

![image](https://user-images.githubusercontent.com/15989893/211616317-260b96da-0632-4150-a985-28cf707da973.png)

2023-01-13 17:40 UTC, pritamstyz4ever commented
The UI doesn't look as per the mocks, the jobs inside the stage should be vertically aligned we can set the arrows from top to bottom. I think that would be more intuitive for users rather than having horizontal alignment and forcing users to scroll right which is not a good experience.

2023-01-13 17:49 UTC, pritamstyz4ever requested changes
Please work on the UI design as per the mocks

2023-01-19 22:45 UTC, sagar1312 commented
> I tried a sample PR: https://cd.screwdriver.cd/pipelines/9762/events/704140
> 
> The `Y_DISPLAYMENT` on row1 and row2 are good, and on row3 is not.
> 
> ![image](https://user-images.githubusercontent.com/15989893/211616317-260b96da-0632-4150-a985-28cf707da973.png)

@adong 
This has been fixed by the last commit

<img width="394" alt="image" src="https://user-images.githubusercontent.com/2124590/213579001-f4a3f878-4959-4082-80f0-10f981415770.png">

2023-01-19 22:47 UTC, sagar1312 commented
Latest changes also dynamically compute and set stage position and height based on stage name and description

2023-01-19 22:51 UTC, sagar1312 commented
> Please work on the UI design as per the mocks

@pritamstyz4ever 
The pipeline/job example in the mock is different. It is not mandatory that stages job/nodes needs to be positioned one below the other

2023-01-23 19:25 UTC, adong commented on app/pipeline/events/template.hbs
> +      stages=stages
I would recommend to keep a copy of the original `workflow-graph-d3` component, and duplicate and refactor the new changes in a new template, i.e. `workflow-graph-stage-d3`. 

So we can move forward, without worrying about: 
1) existing workflow 
2) messing something corner case for the main when soft launching 
3) more flexible to add/remove codes 


```
{{#if stages}}
 {{workflow-graph-stage-d3}}
{{else}}
 {{workflow-graph-d3}}
{{/if}}
```

2023-01-23 20:05 UTC, adong requested changes
See my comment in https://github.com/screwdriver-cd/ui/pull/873/files#r1084458729

2023-02-03 08:00 UTC, sagar1312 commented on app/pipeline/events/template.hbs
> +      stages=stages
Majority of the code (to render stage elements in the workflow graph) with in `workflow-graph-d3` component is already isolated and executed only if stages exist.
https://github.com/screwdriver-cd/ui/pull/873/files#diff-3a03bfd3e46c3280d50d0738c305e3fe169c2729a63e2f0af768070f7ffbbcf9R270

Only [common code](https://github.com/screwdriver-cd/ui/pull/873/files#diff-3a03bfd3e46c3280d50d0738c305e3fe169c2729a63e2f0af768070f7ffbbcf9R219) is applying vertical displacement for existing graph elements like nodes and edges. This is no op when stages are not defined as it always returns `0`.
```
const getVerticalDisplacementByRowPosition = pos => {
      return verticalDisplacementByRowPosition[pos] || 0;
    };
```

I do not see a compelling reason to duplicate 350+ lines of code (plus redundant tests) when there is no complex interleaving logic.

2024-02-06 19:54 UTC, adong submitted a review, later dismissed

2024-02-06 19:54 UTC, adong commented on app/components/workflow-graph-d3/component.js
> +    const stagesGroupedByRowPosition = groupBy(data.stages, 'pos.y');
Minor: can you add more comments to explain the calculation?

2024-02-08 17:48 UTC, adong approved these changes

2024-02-08 18:00 UTC, pritamstyz4ever approved these changes
Blanket approving now, I will review later

2024-02-08 18:09 UTC, merged