fix: update pipelines from different tabs
screwdriver-cd/ui pull request #874
Opened 2023-01-04 19:31 UTC by banusha2

## Context

## Objective

## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-01-10 16:58 UTC, adong requested changes
1) Semantic error, these shuttle APIs are async. So await is needed, with try catch logics to guard. 

```
    try {
      const x = await y();
      // logics
    } catch (e) {
      // stuff
    } 
```

2) How does using the new API endpoints solves the multi-tab issues? 

_(For context purposes, Can you add 1) the issue link, 2) and the related PR backend change if any to the current PR description? )_

Say, one has 2 pages to edit the same collection.

1. Deleting pipelines from collection on page 1
2. Check page 2, not reflecting the changes, and one has to refresh the page to see it

The reason one sees such behavior is that: 
Each webpage has its own data stored in memory. `localStorage` and `sessionStorage` are shared across tabs within the same browser.

Say, we could use `localStorage` to handle it. Then what about the case that page 1 is now in Chrome, and page 2 is now in Firefox. `localStorage` will not share across different apps. 


__HINT__: 
I think, just refactoring the API endpoints from `collection.save()` method to `shuttle`'s api service, will NOT solve the problem underneath. 

The issue to me still inside the part 1) that how one handles the `success` and `error` case

2023-01-10 18:43 UTC, adong commented
1) fetch the latest pipelines before updating anything. (logics already implemented) 
```
      return this.store
        .findRecord('collection', collectionId)
        .then(collection => {
```

2) fetch alone is not enough, also need to _store_ the fetched data, such as pipelines, so if there were newly added or deleted pipelines, the UI will reflect that (_I think_ this is the part that current PR stucks on)

3) Handle the **success** and **error** cases, what if the pipeline ids that are being deleted have already been deleted in the backend, or, what about such a collection itself already being deleted?

2023-01-10 18:55 UTC, adong commented on app/shuttle/service.js
> +    const query = decodeURIComponent($.param({ ids: pipelineIds }));
Why do you use `decodeURIComponent` and `$.param`?

I dont think these functions are needed

2023-01-10 18:56 UTC, adong commented on app/shuttle/service.js
> +    const query = decodeURIComponent($.param({ ids: pipelineIds }));
Same here, `decodeURIComponent` and `$.param` are not needed

2023-01-10 19:06 UTC, adong commented on app/dashboard/show/controller.js
> +          this.shuttle.updateCollection(collectionId, addedPipelineIds);
FYI, `shuttle.updateCollection` is an `async` function, so needs to add `return` in front of it when inside `then` for using promise syntax. 

Also want to point out that using shuttle api to call the backend, will result in the `collection.pipelineIds` being out of sync because `collection.save` were not used.

2023-01-10 20:53 UTC, adong commented on app/dashboard/show/controller.js
> +          this.shuttle.removePipeline(collectionId, pipelineId);
How about moving `this.shuttle.removePipeline(collectionId, pipelineId);` to right before the `return this.store`? 


It would make the logic easier: UPDATE data, and GET data.

2023-01-10 20:54 UTC, adong commented on app/dashboard/show/controller.js
> +          this.shuttle.removeMultiplePipelines(collectionId, removedPipelineIds);
How about moving `this.shuttle.removePipeline(collectionId, pipelineId);` to right before the `return this.store`? 


It would make the logic easier: UPDATE data, and GET data.

2023-01-11 19:08 UTC, adong commented on app/dashboard/show/controller.js
> +          this.shuttle.removeMultiplePipelines(collectionId, removedPipelineIds);
For sequential order purpose, either change to chained promises or use async/await. I prefer the latter approaches with try catch.

2023-01-11 19:12 UTC, adong commented on app/dashboard/show/controller.js
> +          this.shuttle.removePipeline(collectionId, pipelineId);
Something like:
```
try {
  await this.shuttle.removePipeline(collectionId, pipelineId);
  await this.store.findRecord('collection', collectionId)
} catch 
```

2023-01-12 15:43 UTC, banusha2 commented on app/shuttle/service.js
> +    const query = decodeURIComponent($.param({ ids: pipelineIds }));
Removed `decodeURIComponent` , but `$.param` is needed I think to make a query params like this `/collections/123/pipelines?ids[]=11&ids[]=23` from an array

2023-01-13 16:42 UTC, adong commented on app/dashboard/show/controller.js
> +        return collection.save();
I think `return collection.save();` is not necessary. Since `collection` itself was not changed after fetch.

2023-01-13 16:42 UTC, adong commented on app/dashboard/show/controller.js
> +        return collection.save();
I think `return collection.save();` is not necessary. Since `collection` itself was not changed after fetch.

2023-01-13 16:42 UTC, adong commented on app/dashboard/show/controller.js
> +        return collection.save();
I think `return collection.save();` is not necessary. Since `collection` itself was not changed after fetch.

2023-01-13 16:44 UTC, adong commented on app/dashboard/show/controller.js
> +        return e;
Also here in the catch, I think there can be a case depending on the returned response, that says: "pipeline x is has been already added to collection y", or something like that. I'm not sure how the backend response to duplicate, and you can explore more.

2023-01-13 16:44 UTC, adong commented on app/dashboard/show/controller.js
> +        return e;
Similar here, like "pipeline x, y, z already removed from collection y"

2023-01-13 16:45 UTC, adong commented on app/dashboard/show/controller.js
> +        return e;
Similar here, like "pipeline x already removed from collection y" in the catch case.

2023-01-13 17:01 UTC, banusha2 commented on app/dashboard/show/controller.js
> +        return e;
Sorry, didnt get you here

2023-01-13 17:19 UTC, banusha2 commented on app/dashboard/show/controller.js
> +        return e;
Backend does not return an error in case of duplications, just checked it still returns `204`

2023-01-17 20:32 UTC, adong commented
PR https://github.com/screwdriver-cd/ui/pull/875/files merged, and see PR files for more details

2023-01-19 22:23 UTC, adong approved these changes

2023-01-19 22:24 UTC, merged