feat: Add template details page
screwdriver-cd/ui pull request #880
Opened 2023-02-16 20:47 UTC by banusha2

## Context

If users use a template inside their sd.yaml for jobs, the build details page should show something similar as we do for the container images.

## Objective
<img width="1292" alt="Screen Shot 2023-02-16 at 11 35 32 AM 1" src="https://user-images.githubusercontent.com/104225232/219451753-af3c1c3f-de8a-4936-9d5b-4d9e37f81a2e.png">

## References
https://github.com/screwdriver-cd/screwdriver/issues/2822

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-02-16 21:03 UTC, adong commented on app/components/build-banner/template.hbs
> +    <li class="template-info">
Also need to check if `getTemplate.content` has value or not. Otherwise, it will throw errors.

2023-02-16 21:04 UTC, adong commented on app/shuttle/service.js
> +      return {};
Non-valid value such as `{}` needs to be checked in `template.hbs`

2023-02-16 21:04 UTC, adong requested changes
Needs to add tests

2023-02-16 21:06 UTC, adong commented on app/components/build-banner/template.hbs
> +      <span class="banner-value"><a href={{getTemplate.content.link}}>{{getTemplate.content.name}}:{{getTemplate.content.version}}</a></span>
Use `<a>` link redirection is not good, please use ember `{{link-to}}`, you can search our codebase for example

2023-02-16 21:09 UTC, adong commented on app/components/build-banner/component.js
> +  getTemplate: computed('templateId', {
Please rename `getTemplate` to `template` if not already used. We don't need to use verb in the variable, usually verb is used for actions.

2023-02-16 21:10 UTC, adong commented on app/components/build-banner/component.js
> +        promise: this.shuttle.getTemlateDetails(templateId).then(template => {
like `shuttle.getTemlateDetails` is fine to use `get`

2023-02-16 23:52 UTC, tkyi commented on app/shuttle/service.js
> +      return temlateDetails;
```suggestion
   * getTemplateDetails
   * @param {Number} templateId template id
   * @return {Promise} template details
   */
  async getTemplateDetails(templateId) {
    const method = 'get';
    const url = `/template/${templateId}`;

    try {
      const templateDetails = await this.fetchFromApi(method, url);

      return templateDetails;
```

2023-02-16 23:53 UTC, tkyi commented on app/components/build-banner/component.js
> +        promise: this.shuttle.getTemlateDetails(templateId).then(template => {
```suggestion
        promise: this.shuttle.getTemplateDetails(templateId).then(template => {
```

2023-02-16 23:53 UTC, tkyi requested changes
tests?

2023-02-17 15:23 UTC, banusha2 commented on app/components/build-banner/component.js
> +        promise: this.shuttle.getTemlateDetails(templateId).then(template => {
removing`this` gives error that shuttle is not define

2023-02-17 16:49 UTC, adong approved these changes

2023-02-17 16:50 UTC, merged