fix: file name with ampersand error
screwdriver-cd/ui pull request #887
Opened 2023-02-28 17:43 UTC by banusha2

## Context

If an artifact has a filename with an ampersand in it,UI shows an error .
## Objective

<img width="1271" alt="Screen Shot 2023-02-24 at 11 30 21 AM" src="https://user-images.githubusercontent.com/104225232/221932091-2b2a92e1-8cf6-4a28-966d-3b35c88bf02a.png">

## References

https://github.com/screwdriver-cd/screwdriver/issues/2839
## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-02-28 18:37 UTC, adong requested changes
This feature is still under testing.

2023-02-28 18:41 UTC, adong commented
![image](https://user-images.githubusercontent.com/15989893/221948492-ba13c32c-4686-41f8-b927-4fefd83e3320.png)

2023-03-01 22:18 UTC, adong commented on app/components/artifact-tree/component.js
> +      const artifactPath = pathArray[pathArray.length - 1];
Still does not work for me

2023-03-02 15:40 UTC, banusha2 commented on app/components/artifact-tree/component.js
> +      const artifactPath = pathArray[pathArray.length - 1];
What is not working? means you cannot open file with ampersand in it?

2023-03-02 17:13 UTC, adong commented on app/components/artifact-tree/component.js
> +      const artifactPath = pathArray[pathArray.length - 1];
Correct. I test branch with internal production, and cannot open artifacts with this url

```
<screwdriver-url>/pipelines/1015452/builds/34724462/artifacts/cypress/screenshots/common/dashboards/performance.js/Performance%20Dashboard%20tests%20--%20App%20&%20Website%20tests%20--%20should%20show%20data%20after%20switching%20to%20UTC%20timezone%20(failed)%20(attempt%202).png
```

2023-03-02 20:44 UTC, adong commented
It turns out not to be a UI issue, closed.

2023-03-02 20:44 UTC, closed without merging