fix: unable to see build display name
screwdriver-cd/ui pull request #908
Opened 2023-03-21 20:35 UTC by banusha2

## Context

Unable to see display name on Build Details or Options, and unable to see "real" name on Overview.

## Objective
All UI views should be consistent about which name is used for a job.

<img width="1277" alt="Screenshot 2023-03-21 at 12 37 34 PM" src="https://user-images.githubusercontent.com/104225232/226734134-411916fc-ade7-460a-8cc6-e1a0a1dc7254.png">

## References
https://github.com/screwdriver-cd/screwdriver/issues/2773

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-03-21 22:31 UTC, tkyi commented
Can't tell from the screenshot what is different. Is it just the display name for the pipeline at the top?

2023-03-22 15:54 UTC, adong requested changes

2023-03-22 15:54 UTC, adong commented on tests/integration/components/pipeline-list-view/component-test.js
> +        annotations: {
These are fixing the existing tests, can you add a test to check the displayName is used instead of the job name?

2023-03-22 16:31 UTC, banusha2 commented on tests/integration/components/pipeline-list-view/component-test.js
> +        annotations: {
Yes

2023-03-22 17:30 UTC, adong commented on app/components/pipeline-list-job-cell/template.hbs
> +      {{this.record.job.jobName}} {{this.build.status}}
can you remove the `{{this.build.status}}` when hovering over the name?

2023-03-22 17:31 UTC, adong commented on app/components/pipeline-list-job-cell/template.hbs
> +      {{this.record.job.jobName}} {{this.build.status}}
I think the `status` is can be shown when hovering over the `job-cell`, which has the dot icon.

2023-03-22 21:01 UTC, adong approved these changes

2023-03-22 21:01 UTC, merged