feat: filter substantial events
screwdriver-cd/ui pull request #914
Opened 2023-04-07 16:55 UTC by banusha2

## Context

When many scheduled/periodic build events (annotation screwdriver.cd/buildPeriodically) which are shown in an event list, substantial events are not shown at first view.
## Objective
<img width="356" alt="Screenshot 2023-04-07 at 12 53 11 PM" src="https://user-images.githubusercontent.com/104225232/230647032-d1a4211c-b777-4a80-baca-ec4a08f5ea74.png">

## References

https://github.com/screwdriver-cd/screwdriver/issues/2849
## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-04-07 17:19 UTC, adong commented on app/components/pipeline-events/component.js
> +    get() {
This `filteredEvents` adds unnecessary complexity :

The logics can go to `events: computed() ... ` in LINE
https://github.com/screwdriver-cd/ui/blob/fix/show-substantial-build-first/app/components/pipeline-events/component.js#L441

2023-04-07 18:11 UTC, banusha2 commented on app/components/pipeline-events/component.js
> +    get() {
Done

2023-04-07 18:45 UTC, jithine requested changes

2023-04-07 18:45 UTC, jithine commented on app/components/pipeline-events/component.js
> +  events: computed('pipelineEvents', 'prEvents', 'currentEventType', 'filterSubstantialEvents', {
please just call it `filterSchedulerEvents`

2023-04-07 18:45 UTC, jithine commented on app/components/pipeline-events/template.hbs
> +            Toggle to filter substantial events:
`Show Scheduler Events`

2023-04-07 18:45 UTC, jithine commented
Also how does this handle pagination when substantial events in the list are periodic builds.

2023-04-09 02:12 UTC, tkyi requested changes
Interaction should be exactly like this existing filter
<img width="1037" alt="Screenshot 2023-04-08 at 7 10 27 PM" src="https://user-images.githubusercontent.com/3230529/230750620-04398723-bef3-4ad7-b6cc-183d4d5d8435.png">

Toggling would remove scheduled events from view

2023-04-09 02:12 UTC, tkyi requested changes
Interaction should be exactly like this existing filter
<img width="1037" alt="Screenshot 2023-04-08 at 7 10 27 PM" src="https://user-images.githubusercontent.com/3230529/230750620-04398723-bef3-4ad7-b6cc-183d4d5d8435.png">

Toggling would remove scheduled events from view

2023-04-13 17:47 UTC, tkyi commented on app/components/pipeline-options/template.hbs
> +                Show Scheduler Events
```suggestion
                Filter Scheduler Events
```

2023-04-14 22:18 UTC, tkyi approved these changes

2023-04-17 16:37 UTC, jithine approved these changes

2023-04-17 16:39 UTC, jithine commented
Also we need to work with design team on how these filters which hides data from event list can be moved/shown right next to the events itself. So that user looking at it can know that it’s a filtered view and some data could be potenitally hidden.

2023-04-17 16:47 UTC, merged