Add pipeline count
screwdriver-cd/ui pull request #943
Opened 2023-07-31 21:29 UTC by nathom

## Context

We want to see the pipelines that are using a given template version.

## Objective

## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-09-06 17:25 UTC, adong commented on app/templates/detail/version/route.js
> +    return params.version;
Why only return `params.version` here?

This will make the code such as

```javascript
setupController(model, params.version)
```

And the model will be only `version`


How about setting 
```javacript
    return {version: params.version};
```
instead?

2023-09-06 19:25 UTC, sagar1312 requested changes

2023-09-06 19:25 UTC, sagar1312 commented on app/components/pipeline-usage-table-branch/template.hbs
> +<a href="{{this.url}}" target="_blank">
Similar rendering is already being done in other places
- listing pipelines under a collection
- listing pipeline search result
- listing child pipelines

I agree with your approach to make this a reusable component, which could eventually replace all the inline rendering being done as listed above.

Let rename the component to something generic `pipeline-branch-cell`

2023-09-06 19:25 UTC, sagar1312 commented on app/components/pipeline-usage-table-branch/template.hbs
> +{{yield}}
```suggestion
{{yield}}

```

2023-09-06 19:25 UTC, sagar1312 commented on app/components/pipeline-usage-table-name/template.hbs
> +<LinkTo @route="pipeline" @model={{this.pipelineId}}>
Similar rendering is already being done in other places
- listing pipelines under a collection
- listing pipeline search result
- listing child pipelines

I agree with your approach to make this a reusable component, which could eventually replace all the inline rendering being done as listed above.

Let rename the component to something generic `pipeline-name-cell`

2023-09-06 19:25 UTC, sagar1312 commented on app/components/pipeline-usage-table-name/template.hbs
> +  {{this.name}}
All other pages are using `scmRepo.name`. Let us be consistent
```suggestion
  {{this.scmRepo.name}}
```

2023-09-06 19:25 UTC, sagar1312 commented on app/components/template-version-pipeline-usage/component.js
> +      propertyName: 'admins'
We may have add a new component for custom rendering.
- when there are multiple admins, concatenate the names separated by comma.
- when the concatenated text exceeds certain number of characters, show ellipsis. Display the complete text as a tooltip on hover.

2023-09-06 19:25 UTC, sagar1312 commented on app/components/template-version-pipeline-usage/component.js
> +  userSettings: service(),
Why do we need this?

2023-09-06 19:25 UTC, sagar1312 commented on app/templateusage/index/controller.js
> +  userSettings: service(),
why do we need this?

2023-09-06 19:25 UTC, sagar1312 commented on app/templateusage/index/controller.js
> +  pipelineMetrics: computed('routeParams', {
What we are fetching list of pipelines using the template. There are no metrics retrieved.
```suggestion
  pipelines: computed('routeParams', {
```

2023-09-06 19:25 UTC, sagar1312 commented on app/template/service.js
> +  getTemplatePipelineUsage(name, namespace, version) {
API call seems to be failing
![image](https://github.com/screwdriver-cd/ui/assets/2124590/0310f143-76bd-4c00-8ae3-e4b3ffa1ab6b)

2023-09-06 19:27 UTC, sagar1312 commented on app/components/template-version-pipeline-usage/component.js
> +      propertyName: 'admins'
This could be addressed in a follow up PR

2023-09-07 18:37 UTC, nathom commented on app/components/pipeline-usage-table-name/template.hbs
> +  {{this.name}}
It's not the scmRepo name, it's the branch name.

2023-09-07 18:39 UTC, nathom commented on app/components/pipeline-usage-table-name/template.hbs
> +  {{this.name}}
This is the record

```js
        return {
          id: m.id,
          name: m.name,
          branch: branchWithDir,
          url: m.scmRepo.url,
          lastRunDate: lastRun,
          admins: Object.keys(m.admins)
        };
```

2023-09-08 13:38 UTC, sagar1312 commented on app/components/template-version-pipeline-usage/component.js
> +          name: m.name,
```suggestion
          name: m.scmRepo.name,
```

2023-09-08 13:38 UTC, sagar1312 commented on app/components/template-version-pipeline-usage/component.js
> +          url: m.scmRepo.url,
```suggestion
          scmUrl: m.scmRepo.url,
```

2023-09-08 13:38 UTC, sagar1312 commented on app/components/pipeline-usage-table-name/template.hbs
> +  {{this.name}}
It should be corrected in the `app/components/template-version-pipeline-usage/component.js`
to set `pipeline.scmRepo.name` as name instead of `pipeline.name`

2023-09-08 13:38 UTC, sagar1312 commented on app/templateusage/index/controller.js
> +  pipelineMetrics: computed('routeParams', {
Not addressed yet

2023-09-08 13:41 UTC, sagar1312 commented on app/components/pipeline-usage-table-name/template.hbs
> +<LinkTo @route="pipeline" @model={{this.pipelineId}}>
Not addressed

2023-09-08 13:43 UTC, merged