fix: only mark warning on successful build
screwdriver-cd/ui pull request #956
Opened 2023-10-13 16:52 UTC by klu909

## Context

it could confusing to users when failed builds are marked with warning
## Objective

only mark successful builds
## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-10-13 17:05 UTC, jithine reviewed
This looks like something UI shouldn't handle directly. Should we leave the STATUS override logic to API ?

2023-10-13 19:20 UTC, klu909 commented
> This looks like something UI shouldn't handle directly. Should we leave the STATUS override logic to API ?

we will keep it this way for now, main value was warning in build detail page which you wouldn't really get when fetching builds by calling api directly

2023-10-13 20:51 UTC, jithine approved these changes

2023-10-18 02:31 UTC, adong commented on app/components/workflow-graph-d3/component.js
> +            ) {
I'd say use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

`build?.meta?.build?.warning && build.status === 'SUCCESS'`

2023-10-18 02:31 UTC, adong commented on app/pipeline/jobs/index/controller.js
> +              ) {
Same `build?.meta?.build?.warning && build.status === 'SUCCESS'`

2023-10-18 02:32 UTC, adong commented on app/utils/metric.js
> +        if (build.meta && build.meta.build && build.meta.build.warning) {
`if (build?.meta?.build?.warning)`

2023-10-18 02:33 UTC, adong commented on app/utils/metric.js
> +      if (build.meta && build.meta.build && build.meta.build.warning) {
Same `if (build?.meta?.build?.warning)`

2023-10-18 02:41 UTC, adong commented on app/utils/metric.js
> +  if (lastEvent && lastEvent.builds && lastEventStatus === 'success') {
For consistency reasons from the current file, I would use upper-case instead.
`lastEvent?.builds && build.status === 'SUCCESS'` 

Remove 
```
let lastEventStatus = lastEvent.status.toLowerCase();
```

2023-10-18 02:41 UTC, adong commented on app/utils/metric.js
> +    statusColor: getColor(lastEventStatus),
And keep `statusColor: getColor(lastEvent.status.toLowerCase())`

2023-10-18 02:41 UTC, adong requested changes
See comments for code readability improvements

2023-10-19 18:07 UTC, adong approved these changes

2023-10-19 20:31 UTC, merged