feat: add functions to validate pipeline template
screwdriver-cd/ui pull request #984
Opened 2024-01-25 17:33 UTC by pritamstyz4ever

## Context

Enhance validator to support pipeline templates

## Objective

This PR adds logic to check if the supplied yaml is a pipeline template and calls the back API accordingly

## References

## License
https://github.com/screwdriver-cd/screwdriver/issues/2135

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2024-01-25 17:38 UTC, pritamstyz4ever commented
@adong should we also include text for pipeline templates here
<img width="708" alt="Screenshot 2024-01-25 at 12 38 12 PM" src="https://github.com/screwdriver-cd/ui/assets/4926830/816e74c5-df92-44a7-a8c9-952831fd27fd">

2024-01-25 17:51 UTC, adong commented on app/validator/service.js
> +    return /^name|\n+name: |\n+namespace: |\n+config:\s*\n\s*jobs: /.test(yaml);
Maybe change to `isJobTemplate`. Yea, it's tedious

2024-01-25 18:02 UTC, adong commented on app/validator/service.js
> +      url += '/pipeline/template/validate';
We dont validate against API directly. We validate against this template validator.

Repo is: https://github.com/screwdriver-cd/template-validator

Can we move this endpoint to `/validator/template/pipeline`

2024-01-25 18:04 UTC, adong requested changes

2024-01-25 18:04 UTC, adong commented on tests/unit/validator/service-test.js
> +      'http://localhost:8080/v4/pipeline/template/validate',
I think it needs some refactoring for the encapsulation in validator

2024-01-25 18:10 UTC, pritamstyz4ever commented on app/validator/service.js
> +      url += '/pipeline/template/validate';
I don't think we validate directly via template-validator, we call the API which in turn calls the templateValidator
<img width="1918" alt="Screenshot 2024-01-25 at 1 08 07 PM" src="https://github.com/screwdriver-cd/ui/assets/4926830/40efda8e-c53b-436b-be50-5f483be0bacf">

2024-01-25 19:31 UTC, adong commented on app/validator/service.js
> +      url += '/pipeline/template/validate';
Correct, we still calls API. API contains https://github.com/screwdriver-cd/screwdriver/blob/d165071e9ec163c1c746f45781b3176d8a68c4e2/plugins/validator.js, which calls https://github.com/screwdriver-cd/screwdriver/blob/d165071e9ec163c1c746f45781b3176d8a68c4e2/plugins/template-validator.js#L5

I think the template validator has been updated to support job template, https://github.com/screwdriver-cd/screwdriver/commit/2bf13ed3971e9c627aeb5657d4eee6dc211e7e85#diff-12e32795e740f0d1bae40c44544e6f6ce975a060c1caef154ce087c7245a4d3dL6

Maybe @klu909 could help you out.

2024-01-25 20:21 UTC, pritamstyz4ever commented on app/validator/service.js
> +      url += '/pipeline/template/validate';
@adong the pipeline template validation API is here https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/pipelines/templates/validate.js#L10

2024-01-25 21:35 UTC, adong commented on app/validator/service.js
> +      url += '/pipeline/template/validate';
I'm saying, our validator APIs are:

```
/v4/validator
/v4/validator/template   # for job template
```

So the new pipeline template API ought to be
`/v4/validator/template/pipeline`

Instead of 
`/v4/pipeline/template/validate`

2024-02-07 19:22 UTC, VonnyJap commented on app/validator/service.js
> +      url += '/pipeline/template/validate';
I do agree that consistency matters, like in this case `/v4/validator/template/pipeline` seems to be a better endpoint for validating the pipeline template. 

@pritamstyz4ever - would that be lots of refactoring to do so?

2024-02-15 16:42 UTC, adong commented on app/validator/service.js
> +    return /^(?=.*\bnamespace:)(?=.*\bname:)(?=.*\bconfig:.*\bjobs:).*/.test(
Question: what is the subtle difference between `isJobTemplate` and `isPipelineTemplate` in these 2 regex(es)? How does UI know a given string is a `job` or `pipeline` template?

2024-02-15 16:48 UTC, pritamstyz4ever commented on app/validator/service.js
> +      url += '/pipeline/template/validate';
@VonnyJap  
No, we will not be using `/v4/validator` endpoint as it breaks the design.
All the APIs are structured as per the entity they belong to like `pipelines` , `jobs`, `builds`, `commands` etc. , the validator API is an anti-pattern that has `jobs` and `commands` combined and we don't want to add anything new in there. In the future, we will retire this endpoint and move the validation for jobs to `/templates/validate` and similarly for commands to `/commands/validate`

2024-02-15 16:52 UTC, pritamstyz4ever commented on app/validator/service.js
> +    return /^(?=.*\bnamespace:)(?=.*\bname:)(?=.*\bconfig:.*\bjobs:).*/.test(
both types of templates have different configuration, for pipeline templates we need the config to always specify jobs so we check for `config.jobs`, `namespace` and `name`

2024-03-01 20:41 UTC, VonnyJap approved these changes

2024-03-04 23:40 UTC, merged